// The card game's half of the From The Depths battle-result handshake.
//
// A `.customBattle` file generated by `customBattle.ts` carries a `CardGame`
// block holding a short-lived token; a mod running inside FtD reads the battle
// outcome and POSTs it back to the `battle-report` edge function with that
// token. This module is the part BOTH ends of that exchange have to agree on —
// the browser mints the battle key when it builds the file and the function
// verifies it, and the alive-fraction → HP rule has to be one number in one
// place rather than one in Deno and another in C#.
//
// It deliberately imports NOTHING — not even `gameSettings.ts`. Reading a
// battle's identity and turning alive fractions into HP percentages needs only
// plain JSON fields, and staying dependency-free is what lets `battle-report`
// declare ONE file in `supabase/functions/shared-manifest.json` instead of
// copying the engine's whole module graph. CLAUDE.md's "consumers import
// `shared/engine/index.ts`, never individual engine modules" rule exists for
// the handler/effect registries; `battle-report` dispatches no action and
// needs neither.

/**
 * Wire-format version, written as `CardGame.Version` and echoed by the mod.
 *
 * Bump it only for a breaking change to either the block or the `submit` body,
 * and bump the mod in the same breath — an old mod reading a new file is the
 * failure this number exists to make legible.
 */
export const BATTLE_REPORT_WIRE_VERSION = 1

/**
 * How long a battle token stays redeemable.
 *
 * Long enough for two captains to run a fight over Discord in one evening,
 * short enough that a token left in a Downloads folder stops being a live
 * credential by morning. Single use and the battle-key check below are the
 * real bounds; this is the backstop.
 */
export const BATTLE_TOKEN_TTL_MS = 12 * 60 * 60 * 1000

/** Upper bound on the vehicles one `submit` may name — bounds the stored jsonb. */
export const MAX_REPORTED_VEHICLES = 64

/**
 * The subset of `state.activeBattle` that identifies WHICH battle this is.
 *
 * Typed structurally rather than importing `ActiveBattle` from
 * `engine/engineTypes.ts`, for the no-dependencies reason above.
 */
export interface BattleIdentity {
  zoneId: number
  aggressor: string
  attackerIds: string[]
  defenderIds: string[]
}

/**
 * A stable fingerprint of one battle, carried in the file and echoed by the mod.
 *
 * It is what stops a token minted for an earlier battle from reporting into a
 * later one: `battle-report` recomputes this from the live `games` row and
 * refuses a mismatch.
 *
 * Two things are deliberately absent:
 *
 *   * **`distanceM`.** Tactical Positioning is legal while a battle stands
 *     (`BattleOverlay` offers it, `USE_HERO_POWER` is in BATTLE_ACTIONS), so
 *     including the distance would invalidate a token the moment either
 *     captain nudged the range — after the player had already downloaded the
 *     file and started fighting.
 *   * **`summons`.** They need no term of their own: a summon's instanceId is
 *     already in `attackerIds`/`defenderIds` (that is how
 *     `battleParticipants` finds it before falling back to the summon map), so
 *     a battle that gains one changes this key through those lists.
 *
 * The ids are sorted so the key does not depend on the order either side
 * happened to list them in.
 */
export function battleKeyOf(battle: BattleIdentity): string {
  const ids = (xs: string[]): string => [...xs].sort().join(',')
  return [
    battle.zoneId, battle.aggressor, ids(battle.attackerIds), ids(battle.defenderIds),
  ].join('|')
}

/**
 * Which side a reported `winningTeamIndex` refers to.
 *
 * The mod reports a TEAM index, because a team is all FtD knows about. Turning
 * that back into a card-game side rests on one convention: `battleTeams.ts`
 * always emits the **aggressor first, defender second**, and
 * `buildCustomBattle` writes `Teams` in the order it is handed. Both the file's
 * `Teams` and its `CardGame.Teams` come from that same array, so index 0 is the
 * aggressor in both.
 *
 * Kept here, next to the wire format, rather than derived at each call site —
 * and returning null for an index that is neither, rather than guessing.
 */
export function sideForTeamIndex(aggressor: string, index: number): string | null {
  if (index === 0) return aggressor
  if (index === 1) return aggressor === 'a' ? 'b' : 'a'
  return null
}

/** One vehicle's outcome as the mod reports it. Every field but the id is optional and distrusted. */
export interface FtdVehicleOutcome {
  instanceId: string
  name?: string
  /** 0..1, FtD's own notion of how much of the hull is left. */
  aliveFraction?: number
  /** False when the vehicle is no longer in the world at battle end. */
  exists?: boolean
  disqualified?: boolean
}

export interface FtdBattleResultInput {
  winningTeamIndex?: number
  vehicles?: unknown
}

/**
 * Alive fraction → the 0-100 HP percentage `SUBMIT_BATTLE_REPORT` wants.
 *
 * Direct and clamped; a vehicle that no longer exists is 0.
 *
 * ⚠ **Known, accepted sharp edge.** FtD's own cleanup rules — written by
 * `defaultRules()` in `customBattle.ts` as `TooDamaged: 0.55` and
 * `DamagedAndSinking: 0.8` — remove a hull from the world well before its
 * alive fraction reaches zero. So a hull FtD despawned lands here at **0**,
 * not somewhere in the repair band (REPAIR_WINDOW_MIN_PERCENT ..
 * SURVIVE_HP_PERCENT in `gameSettings.ts`), and a captain who would have paid
 * to repair it sees a wreck instead.
 *
 * This is harmless precisely because the prefill is advisory: nothing here
 * submits anything. The numbers land in `BattleOverlay`'s report form, a human
 * reads them, adjusts the ones FtD rounded off, and presses Submit — and the
 * opponent still has to approve. Do not "fix" this by inventing a floor for
 * despawned hulls; that would guess at a number the players can just look at.
 */
export function hpFromVehicle(v: FtdVehicleOutcome): number {
  if (v.exists === false) return 0
  const raw = typeof v.aliveFraction === 'number' && Number.isFinite(v.aliveFraction)
    ? v.aliveFraction
    : 0
  return Math.max(0, Math.min(100, Math.round(raw * 100)))
}

export type PrefillResult =
  | { ok: true; results: Record<string, number>; names: Record<string, string> }
  | { ok: false; error: string }

/**
 * Validate a mod's `submit` body and turn it into the `results` map the report
 * form prefills from.
 *
 * Every failure message is written for a **player**, not a developer: the mod
 * shows it in an in-game popup, where "expected object" would be useless. This
 * is a shape check, not an authority check — it deliberately does NOT verify
 * that the ids are the battle's real roster. That check belongs to
 * `SUBMIT_BATTLE_REPORT`, which already refuses a report that does not cover
 * exactly `battleParticipants`, and duplicating it here would mean teaching
 * `battle-report` the whole engine to enforce something the engine enforces
 * anyway (see the header). A wrong id simply prefills nothing for that hull.
 */
export function buildPrefillResults(input: FtdBattleResultInput): PrefillResult {
  const list = input.vehicles
  if (!Array.isArray(list)) {
    return { ok: false, error: 'The battle report is missing its list of vehicles.' }
  }
  if (list.length === 0) {
    return { ok: false, error: 'The battle report named no vehicles.' }
  }
  if (list.length > MAX_REPORTED_VEHICLES) {
    return {
      ok: false,
      error: `The battle report named ${list.length} vehicles; at most ${MAX_REPORTED_VEHICLES} are accepted.`,
    }
  }
  const results: Record<string, number> = {}
  const names: Record<string, string> = {}
  for (const raw of list) {
    if (typeof raw !== 'object' || raw === null) {
      return { ok: false, error: 'The battle report contains an entry that is not a vehicle.' }
    }
    const v = raw as FtdVehicleOutcome
    if (typeof v.instanceId !== 'string' || v.instanceId === '') {
      return { ok: false, error: 'A vehicle in the battle report has no instance id.' }
    }
    if (Object.hasOwn(results, v.instanceId)) {
      return { ok: false, error: `The battle report lists ${v.name ?? 'a vehicle'} twice.` }
    }
    results[v.instanceId] = hpFromVehicle(v)
    if (typeof v.name === 'string' && v.name !== '') names[v.instanceId] = v.name
  }
  return { ok: true, results, names }
}
