import { readdirSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, join } from 'node:path'
import { v5 as uuidv5 } from 'uuid'
import type { SeedCard, SeedHeroPower, VehicleType } from '../../shared/types'

// Fixed namespace: changing it changes every seeded id. Never change it.
const FTD_NAMESPACE = 'a1b0c7e2-4f3d-4b6a-9e8c-2d5f7a9b1c3e'

export const cardId = (faction: string, name: string): string =>
  uuidv5(`card:${faction}:${name}`, FTD_NAMESPACE)

export const heroPowerId = (faction: string, name: string): string =>
  uuidv5(`hero:${faction}:${name}`, FTD_NAMESPACE)

const SOURCE_DIR = join(dirname(fileURLToPath(import.meta.url)), 'source')

// Upstream bug in supabase/seed/source/builtInCards/OW-Built-in.js: these 10
// cards set `vehicleType: VEHICLE_TYPES.ship` (lowercase key), but the old
// BE's VEHICLE_TYPES enum only has uppercase keys (SHIP, AIRSHIP, TANK,
// PLANE, SUB), so `VEHICLE_TYPES.ship` evaluates to `undefined`. We patch it
// here instead of editing the source file, which stays a verbatim copy of the
// old BE data.
//
// The typo also means the source cannot be trusted on WHICH type was meant —
// `.ship` was written on a flyer too. Rook is one: From The Depths' own
// Neter.faction entry gives it BlueprintType 9, the air class (Eyrie, Nimbus,
// Damacy), where the other nine carry BlueprintType 2 — as do 53 of the cards
// already typed 'ship'. It also spawns through the air delegate at 200 m and
// puts its lowest block at y=+3, the only one of the ten whose hull sits
// entirely above the waterline. Airship rather than plane is a balance call:
// 3,180 blocks at a 98,841 blueprint cost is a heavy castle-flyer, so it is
// Judgement prey and takes Martyr's boosted attack count.
const VEHICLE_TYPE_PATCHES: Record<string, VehicleType> = {
  'OW:Cauldron': 'ship',
  'OW:Clydesdale': 'ship',
  'OW:Halberd': 'ship',
  'OW:Iron Cordon': 'ship',
  'OW:Javelin': 'ship',
  'OW:Jormangund': 'ship',
  'OW:Mace': 'ship',
  'OW:Mandrel': 'ship',
  'OW:Partisan': 'ship',
  'OW:Rook': 'airship',
}

export async function loadSeedData(): Promise<{
  cards: SeedCard[]
  heroPowers: SeedHeroPower[]
}> {
  const cardsDir = join(SOURCE_DIR, 'builtInCards')
  const byKey = new Map<string, SeedCard>()
  for (const file of readdirSync(cardsDir).filter((f) => f.endsWith('.js')).sort()) {
    const mod = await import(pathToFileURL(join(cardsDir, file)).href)
    for (const value of Object.values(mod)) {
      if (!Array.isArray(value)) continue
      for (const card of value as SeedCard[]) {
        if (!card?.name || !card?.faction) {
          throw new Error(`Malformed card in ${file}: ${JSON.stringify(card)}`)
        }
        const key = `${card.faction}:${card.name}`
        if (card.vehicleType == null && VEHICLE_TYPE_PATCHES[key]) {
          card.vehicleType = VEHICLE_TYPE_PATCHES[key]
        }
        const existing = byKey.get(key)
        if (existing) {
          if (JSON.stringify(existing) !== JSON.stringify(card)) {
            throw new Error(`Conflicting duplicate card ${key} in ${file}`)
          }
          continue // identical duplicate: keep first
        }
        byKey.set(key, card)
      }
    }
  }
  const cards = [...byKey.values()].sort((a, b) =>
    `${a.faction}:${a.name}`.localeCompare(`${b.faction}:${b.name}`),
  )
  const heroMod = await import(pathToFileURL(join(SOURCE_DIR, 'heroPowers.js')).href)
  const heroPowers = heroMod.allHeroPowers as SeedHeroPower[]
  return { cards, heroPowers }
}

const q = (s: string): string => `'${s.replace(/'/g, "''")}'`
const qj = (v: unknown): string => `${q(JSON.stringify(v ?? null))}::jsonb`

export function buildSeedSql(cards: SeedCard[], heroPowers: SeedHeroPower[]): string {
  const parts: string[] = ['-- GENERATED by supabase/seed/cli.ts. Do not hand-edit.']
  for (const c of cards) {
    const values = [
      q(cardId(c.faction, c.name)),
      q(c.name),
      'true',
      'null',
      q(c.faction),
      q(c.type),
      c.vehicleType == null ? 'null' : q(c.vehicleType),
      String(c.blueprintCost ?? 0),
      String(c.materialCost ?? 0),
      String(c.cpCost ?? 0),
      q(c.cardText ?? ''),
      q(c.imageUrl ?? ''),
      qj(c.keywords ?? []),
      qj(c.meta ?? {}),
    ]
    parts.push(
      `insert into public.cards (id, name, is_built_in, owner_id, faction, type, vehicle_type, blueprint_cost, material_cost, cp_cost, card_text, image_url, keywords, meta)\n` +
        `values (${values.join(', ')})\n` +
        `on conflict (id) do update set name = excluded.name, is_built_in = excluded.is_built_in, owner_id = excluded.owner_id, faction = excluded.faction, type = excluded.type, vehicle_type = excluded.vehicle_type, blueprint_cost = excluded.blueprint_cost, material_cost = excluded.material_cost, cp_cost = excluded.cp_cost, card_text = excluded.card_text, image_url = excluded.image_url, keywords = excluded.keywords, meta = excluded.meta;`,
    )
  }
  for (const h of heroPowers) {
    parts.push(
      `insert into public.hero_powers (id, name, faction, power_text, cp_cost, meta)\n` +
        `values (${q(heroPowerId(h.faction, h.name))}, ${q(h.name)}, ${q(h.faction)}, ${q(h.text)}, ${String(h.cpCost ?? 1)}, '{}'::jsonb)\n` +
        `on conflict (id) do update set name = excluded.name, faction = excluded.faction, power_text = excluded.power_text, cp_cost = excluded.cp_cost, meta = excluded.meta;`,
    )
  }
  return parts.join('\n')
}
