// GENERATED by scripts/import-ship-profiles.ts from LH.cards.md — do not hand-edit.
// Re-run the importer on a fresh report instead; shared/shipProfiles.test.ts pins
// every key here to a seeded card.
import type { ShipProfile } from '../shipProfiles.ts'

export const LH_SHIP_PROFILES: Record<string, ShipProfile> = {
  "LH:Ampere": {
    "role": "EMP missile skimmer",
    "strength": 1681,
    "rank": 13,
    "type": "Jet-propelled skimmer with a plasma cannon and EMP missiles. 66 m long, 49 m wide, 3,240 blocks.",
    "speed": "121.3 m/s (236 kn) — quicker than 99 in 100 ships.",
    "fightsAt": "1,100 m.",
    "sees": "One radar and two radar trackers, seven laser rangefinders, infrared and telescope trackers, cameras, 15 missile warners, 2 laser warners. No sonar.",
    "summary": "Balanced EMP skimmer. Everything it fires stuns rather than sinks; average firepower and toughness for its price. Designers: 18 battle points, difficulty 1.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "58th percentile — 68 % plasma cannon, the rest EMP missiles"
      },
      "toughness": {
        "score": 3,
        "why": "58th percentile; 51st among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "91st percentile"
      },
      "range": {
        "score": 4,
        "why": "60th percentile"
      },
      "cost": {
        "score": 3,
        "why": "58th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "a plasma cannon, ten radar missiles and six torpedoes — every warhead EMP: it disables, it does not sink"
      },
      "aircraft": {
        "score": 3,
        "why": "plasma cannon on an anti-air mount with a splitter, ten radar-guided missiles, 236 knots; designers 1×"
      },
      "submarines": {
        "score": 2,
        "why": "six sonar-seeking EMP torpedoes but no sonar aboard; designers 0.5×"
      },
      "missiles": {
        "score": 3,
        "why": "20 interceptors, 15 warners, 6 smoke; no shields"
      }
    },
    "verdict": "balanced",
    "verdictDetail": "Firepower 0.93× and toughness 0.96× the per-material median for its price; its edge is 236 knots and EMP, not numbers."
  },
  "LH:Angstrom": {
    "role": "missile cruiser, laser point-defence",
    "strength": 6526,
    "rank": 1,
    "type": "Fast missile cruiser whose laser system is entirely point-defence. 127 m, 6,841 blocks.",
    "speed": "108.8 m/s (212 kn) — quicker than 19 in 20 ships.",
    "fightsAt": "1,500 m.",
    "sees": "Four radar trackers, four camera and four infrared trackers, five laser rangefinders, 6 missile warners, a radio snooper. No all-round radar, no sonar.",
    "summary": "Balanced and missile-proof. The strongest Hoods design by the game's own number (rank 1 of 62); 32 radar missiles behind a 12-node laser point-defence.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "78th percentile — 94 % missiles"
      },
      "toughness": {
        "score": 5,
        "why": "82nd percentile; 50th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "86th percentile"
      },
      "range": {
        "score": 5,
        "why": "86th percentile"
      },
      "cost": {
        "score": 5,
        "why": "83rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "16 large radar missiles (two wide-cone frag warheads), 12 medium frag missiles, four large EMP missiles"
      },
      "aircraft": {
        "score": 3,
        "why": "32 radar-guided missiles can chase aircraft; no gun or laser weapon for the close work; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "no sonar, nothing reaches under water"
      },
      "missiles": {
        "score": 5,
        "why": "laser point-defence with 12 nodes on 162 cavities and 297 pumps, 10 shields, 6 warners"
      }
    },
    "verdict": "balanced, missile-proof",
    "verdictDetail": "Firepower 0.88× and toughness 0.97× the per-material median for its price — ordinary per material, but 212 knots and a point-defence few missile ships get through."
  },
  "LH:Byte": {
    "role": "hover skimmer",
    "strength": 358,
    "rank": 42,
    "type": "Tiny jet skimmer the game classes as a ship — it can climb to 150 m. 29 m long, 27 m wide, 821 blocks.",
    "speed": "105.6 m/s (205 kn) — quicker than 19 in 20 ships.",
    "fightsAt": "1,000 m.",
    "sees": "A radar tracker, a camera and a camera tracker, a radio snooper. No warners.",
    "summary": "Cheap glass cannon. Four fixed particle lenses and four small missiles on an alloy shell. Designers: 20 battle points.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "32nd percentile — half particle cannon, half missiles"
      },
      "toughness": {
        "score": 1,
        "why": "15th percentile; 25th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "85th percentile"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 1,
        "why": "19th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "four small fixed particle lenses on 64 m of tube, four small radar frag missiles"
      },
      "aircraft": {
        "score": 1,
        "why": "fixed lenses; designers 0.4×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 1,
        "why": "no warners, interceptors, shields or decoys"
      }
    },
    "verdict": "cheap glass cannon",
    "verdictDetail": "Firepower 1.7× and toughness 0.64× the per-material median for its price."
  },
  "LH:Candela": {
    "role": "laser battleship",
    "strength": 1569,
    "rank": 16,
    "type": "Laser battleship on jets — twenty laser outputs on a million-material hull that does 213 knots. 163 m long, 53 m wide, 30 m tall, 15,254 blocks.",
    "speed": "109.5 m/s (213 kn) — quicker than 19 in 20 ships.",
    "fightsAt": "1,800 m — longer than 19 in 20 craft.",
    "sees": "Five all-round radars and two trackers, twelve sonar sets, cameras with five trackers, four infrared cameras, seven laser rangefinders, 17 missile warners, two radio snoopers — everything.",
    "summary": "Fast laser fortress. The toughest Hoods design and 4th in firepower, faster than most destroyers; only its lasers stop at the waterline.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "93rd percentile — 93 % laser"
      },
      "toughness": {
        "score": 5,
        "why": "97th percentile; 85th among craft of its price; 1st of 62 Hoods designs"
      },
      "speed": {
        "score": 5,
        "why": "87th percentile"
      },
      "range": {
        "score": 5,
        "why": "95th percentile"
      },
      "cost": {
        "score": 5,
        "why": "95th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "twelve turret lasers and eight short-range lasers on 522 cavities, 982 pumps and 970 frequency doublers; six EMP and six frag missiles"
      },
      "aircraft": {
        "score": 4,
        "why": "twelve turret lasers hit instantly — no lead, no flight time — plus twelve radar missiles; uncalibrated, and smoke or shields blunt it"
      },
      "submarines": {
        "score": 1,
        "why": "twelve sonar sets find them; lasers stop at the surface"
      },
      "missiles": {
        "score": 4,
        "why": "36 interceptors, 12 shields, 17 warners; no laser point-defence node"
      }
    },
    "verdict": "tank",
    "verdictDetail": "Firepower 0.90× and toughness 1.29× the per-material median for its price — and 213 knots."
  },
  "LH:Chrysoprase": {
    "role": "plasma picket boat",
    "strength": 272,
    "rank": 45,
    "type": "Small jet skimmer with one plasma cannon. 49 m, 1,190 blocks.",
    "speed": "92.0 m/s (179 kn) — quicker than 9 in 10 ships.",
    "fightsAt": "950 m — closer than 9 in 10 craft.",
    "sees": "A radar, a camera, an infrared camera, a laser rangefinder, a rangefinder, a radio snooper. No warners.",
    "summary": "Cheap, sturdy picket. One small plasma gun and four missiles, two of them without a warhead. Designers: 10 battle points.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "24th percentile — 70 % plasma cannon"
      },
      "toughness": {
        "score": 2,
        "why": "26th percentile; 55th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "80th percentile"
      },
      "range": {
        "score": 1,
        "why": "7th percentile"
      },
      "cost": {
        "score": 1,
        "why": "17th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "one small plasma cannon and two EMP missiles"
      },
      "aircraft": {
        "score": 1,
        "why": "forward plasma mantlet; designers 0.5×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 1,
        "why": "nothing"
      }
    },
    "verdict": "cheap picket",
    "verdictDetail": "Firepower 1.05× and toughness 1.3× the per-material median for its price — a metal hull makes it sturdier than it looks."
  },
  "LH:Conduit": {
    "role": "cargo and repair ship",
    "strength": 0,
    "rank": 52,
    "rankTied": true,
    "type": "Unarmed cargo and repair ship — twelve repair tentacles, no weapons. 105 m, 3,207 blocks.",
    "speed": "49.2 m/s (96 kn) — quicker than 5 in 6 ships; its designers tell it to cruise.",
    "fightsAt": "1,000 m — it does not fight.",
    "sees": "A radio snooper, nothing else.",
    "summary": "Unarmed freighter. Alloy and lead hull with 74 armour plates; the toughest thing per material on this list, and harmless. Designers: 10 battle points, 0× vs everything.",
    "scores": {
      "firepower": {
        "score": 1,
        "why": "2nd percentile — 0"
      },
      "toughness": {
        "score": 3,
        "why": "54th percentile; 95th among craft of its price"
      },
      "speed": {
        "score": 3,
        "why": "58th percentile overall; 84th among ships"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 2,
        "why": "24th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 1,
        "why": "no weapons"
      },
      "aircraft": {
        "score": 1,
        "why": "no weapons"
      },
      "submarines": {
        "score": 1,
        "why": "no weapons"
      },
      "missiles": {
        "score": 1,
        "why": "nothing but plating"
      }
    },
    "verdict": "freighter, not a warship",
    "verdictDetail": "Toughness 4.0× the per-material median for its price, firepower 0."
  },
  "LH:Eclipse": {
    "role": "armed luxury yacht",
    "strength": 1327,
    "rank": 23,
    "type": "Armed luxury yacht — \"a 5-star hotel on the sea\" with pop-up missile batteries and a hidden laser. 121 m, 5,443 blocks.",
    "speed": "51.7 m/s (100 kn) — quicker than 5 in 6 ships.",
    "fightsAt": "1,300 m.",
    "sees": "Two radars, two passive sonar sets, cameras with two trackers, infrared cameras with two trackers, a laser rangefinder — but a single missile warner.",
    "summary": "Balanced laser yacht. Six lasers, twelve EMP/frag missiles and a 13-node point-defence; exactly average numbers for its price. Designers: 35 battle points, difficulty 1.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "60th percentile — 75 % laser"
      },
      "toughness": {
        "score": 4,
        "why": "61st percentile; 58th among craft of its price"
      },
      "speed": {
        "score": 3,
        "why": "59th percentile; 85th among ships"
      },
      "range": {
        "score": 4,
        "why": "75th percentile"
      },
      "cost": {
        "score": 4,
        "why": "60th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "six lasers on 240 cavities and 130 frequency doublers, twelve missiles with two EMP and two frag warheads each"
      },
      "aircraft": {
        "score": 3,
        "why": "four hull lasers and a two-axis pop-up laser turret hit instantly; twelve radar missiles; designers 1×"
      },
      "submarines": {
        "score": 2,
        "why": "two passive sonar sets; the lasers stop at the surface and the \"torpedoes\" are decoys"
      },
      "missiles": {
        "score": 4,
        "why": "13-node laser point-defence, 12 interceptors, 10 shields — cued by a single warner"
      }
    },
    "verdict": "balanced",
    "verdictDetail": "Firepower 1.00× and toughness 1.08× the per-material median for its price."
  },
  "LH:Impedance": {
    "role": "laser superweapon, flagship-priced",
    "strength": 1199,
    "rank": 24,
    "type": "Laser superweapon on 716 hydrofoils — three triple-laser turrets fed by 2,016 cavities, and a 64-node point-defence. 164 m long, 41 m wide, 34 m tall, 18,861 blocks.",
    "speed": "102.5 m/s (199 kn) — quicker than 19 in 20 ships.",
    "fightsAt": "1,700 m — longer than 9 in 10 craft.",
    "sees": "Two radars, three radar trackers and a passive radar, one active and three passive sonar sets, cameras with four trackers, infrared, four laser rangefinders, 8 missile warners, a retroreflection sensor.",
    "summary": "The biggest laser afloat; leans glass for its price. 1st in firepower of 62 Hoods designs (98th percentile of the whole campaign), 3rd toughest — but three-quarters the toughness of ships its price.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "98th percentile — 99 % laser"
      },
      "toughness": {
        "score": 5,
        "why": "93rd percentile; 43rd among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "83rd percentile"
      },
      "range": {
        "score": 5,
        "why": "93rd percentile"
      },
      "cost": {
        "score": 5,
        "why": "97th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "nine lasers on 2,016 cavities, 2,016 pumps, 1,602 frequency doublers and 128 destabilisers — nothing else on this list comes close"
      },
      "aircraft": {
        "score": 4,
        "why": "three triple-laser turrets hit instantly; eight EMP missiles; uncalibrated"
      },
      "submarines": {
        "score": 1,
        "why": "four sonar sets find them; lasers stop at the surface"
      },
      "missiles": {
        "score": 5,
        "why": "64-node laser point-defence, 24 interceptors, 12 shields, 8 warners"
      }
    },
    "verdict": "leans glass cannon",
    "verdictDetail": "Firepower 1.25× and toughness 0.73× the per-material median for its price — the most destructive thing the Hoods field, paid for in hull."
  },
  "LH:Kilowatt": {
    "role": "laser escort",
    "strength": 0,
    "rank": 52,
    "rankTied": true,
    "type": "Laser escort — two twin laser turrets and nothing else. 82 m, 3,423 blocks.",
    "speed": "85.0 m/s (165 kn) — quicker than 9 in 10 ships.",
    "fightsAt": "1,100 m.",
    "sees": "One radar and two trackers, five sonar sets, cameras and infrared trackers, six laser rangefinders, 7 missile warners, 6 laser warners, a radio snooper.",
    "summary": "Sturdy laser escort. Four laser outputs with 40 destabilisers for a fast dump; the game's strength number ignores lasers, so it scores 0.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "49th percentile — all laser"
      },
      "toughness": {
        "score": 3,
        "why": "58th percentile; 62nd among craft of its price"
      },
      "speed": {
        "score": 4,
        "why": "76th percentile; 91st among ships"
      },
      "range": {
        "score": 4,
        "why": "60th percentile"
      },
      "cost": {
        "score": 3,
        "why": "55th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "two twin laser turrets on 152 cavities, 189 frequency doublers and 40 destabilisers"
      },
      "aircraft": {
        "score": 3,
        "why": "four turret lasers hit instantly; no missiles; uncalibrated"
      },
      "submarines": {
        "score": 1,
        "why": "five sonar sets find them; lasers stop at the surface"
      },
      "missiles": {
        "score": 2,
        "why": "2 shields, a heat and a radar decoy, 2 smoke, 7 warners; no interceptors or point-defence"
      }
    },
    "verdict": "sturdy, hits softly",
    "verdictDetail": "Firepower 0.80× and toughness 1.17× the per-material median for its price."
  },
  "LH:Megawatt": {
    "role": "plasma raider, fleet backbone",
    "strength": 1656,
    "rank": 14,
    "type": "Plasma raider — the mass-built backbone of the Hoods fleet, made to circle Steel Strider battleships and tear them apart. 96 m long, 35 m wide, 4,762 blocks.",
    "speed": "86.5 m/s (168 kn) — quicker than 9 in 10 ships.",
    "fightsAt": "1,000 m.",
    "sees": "Two radars, a radar 90 and two trackers, nine sonar sets, a camera, two infrared trackers, three laser rangefinders, 17 missile warners, 7 laser warners.",
    "summary": "Balanced plasma raider. Two plasma turrets and nine EMP missiles behind a 9-node point-defence. Designers: 42 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "73rd percentile — 94 % plasma"
      },
      "toughness": {
        "score": 4,
        "why": "72nd percentile; 50th among craft of its price"
      },
      "speed": {
        "score": 4,
        "why": "77th percentile; 91st among ships"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 4,
        "why": "74th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "two plasma cannons on 350 generators, nine radar EMP missiles; built for rapid strikes on battleships"
      },
      "aircraft": {
        "score": 3,
        "why": "two plasma turrets on anti-air mantlets and nine radar-guided missiles; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "nine sonar sets find them; nothing reaches under water; designers 0.4×"
      },
      "missiles": {
        "score": 4,
        "why": "9-node laser point-defence, 16 interceptors, 8 shields, 13 smoke, 17 warners"
      }
    },
    "verdict": "balanced",
    "verdictDetail": "Firepower 1.05× and toughness 0.97× the per-material median for its price."
  },
  "LH:Penumbra": {
    "role": "laser cruiser with EMP torpedoes",
    "strength": 1195,
    "rank": 25,
    "type": "Laser cruiser with a pop-up main laser, four close-in laser turrets and nine EMP torpedoes. 125 m, 5,566 blocks.",
    "speed": "69.6 m/s (135 kn) — quicker than 9 in 10 ships.",
    "fightsAt": "1,200 m.",
    "sees": "One radar and two radar 90s, two passive sonar sets, cameras with four trackers, an infrared camera, 21 missile warners, a radio snooper.",
    "summary": "Laser cruiser, leans glass. Six lasers on 704 frequency doublers, an alloy hull two-thirds as tough as its price class.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "76th percentile — 92 % laser"
      },
      "toughness": {
        "score": 4,
        "why": "65th percentile; 29th among craft of its price"
      },
      "speed": {
        "score": 4,
        "why": "68th percentile; 89th among ships"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 4,
        "why": "75th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "six lasers on 248 cavities and 704 frequency doublers; nine EMP torpedoes"
      },
      "aircraft": {
        "score": 3,
        "why": "six turret lasers hit instantly; no missiles; uncalibrated"
      },
      "submarines": {
        "score": 2,
        "why": "nine sonar-seeking torpedoes and two passive sonar sets — but the warheads only stun"
      },
      "missiles": {
        "score": 4,
        "why": "four close-in laser turrets on six controllers, 26 interceptors (16 for torpedoes), 11 shields, 21 warners"
      }
    },
    "verdict": "leans glass cannon",
    "verdictDetail": "Firepower 1.11× and toughness 0.65× the per-material median for its price."
  },
  "LH:Superradiance": {
    "role": "one-beam laser cruiser",
    "strength": 1110,
    "rank": 27,
    "type": "Laser cruiser built around a single enormous beam — one combiner fed by 545 cavities and 220 destabilisers. 133 m long, 41 m wide, 9,388 blocks.",
    "speed": "102.7 m/s (200 kn) — quicker than 19 in 20 ships.",
    "fightsAt": "1,500 m.",
    "sees": "Three radar 90s and six radar trackers, 20 infrared trackers and six infrared cameras, cameras with six trackers, nine laser rangefinders. No sonar, no missile warners.",
    "summary": "One-beam tank. 8th toughest Hoods design; everything it has goes down one barrel. Designers: 1.3× vs surface.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "75th percentile — 99 % laser"
      },
      "toughness": {
        "score": 5,
        "why": "88th percentile; 64th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "83rd percentile"
      },
      "range": {
        "score": 5,
        "why": "86th percentile"
      },
      "cost": {
        "score": 5,
        "why": "86th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "one pulsed beam from 545 cavities, 471 pumps, 585 frequency doublers, 220 destabilisers and 70 Q switches; designers 1.3×"
      },
      "aircraft": {
        "score": 3,
        "why": "one turret laser, instant-hit, with 20 infrared trackers to aim it; no missiles; uncalibrated"
      },
      "submarines": {
        "score": 1,
        "why": "no sonar, nothing reaches under water"
      },
      "missiles": {
        "score": 3,
        "why": "32 interceptors, 13 shields, 4 smoke generators — and no warners to cue the interceptors"
      }
    },
    "verdict": "tank",
    "verdictDetail": "Firepower 0.67× and toughness 1.17× the per-material median for its price."
  },
  "LH:Terawatt": {
    "role": "plasma battleship",
    "strength": 2426,
    "rank": 10,
    "type": "Plasma battleship — two triple plasma turrets and a laser on a hull that is 36 % heavy armour. 131 m long, 41 m wide, 29 m tall, 9,424 blocks.",
    "speed": "116.0 m/s (226 kn) — quicker than 49 in 50 ships.",
    "fightsAt": "1,500 m.",
    "sees": "Four radar 90s, ten radar trackers and a passive radar, four sonar sets, twelve infrared trackers, cameras with six trackers, five laser rangefinders, three rangefinders, 10 missile warners, 6 laser warners, a radio snooper.",
    "summary": "Armoured plasma tank. 2nd toughest Hoods design, 226 knots, and the designers' highest-rated card here: 50 battle points, difficulty 3.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "85th percentile — 92 % plasma"
      },
      "toughness": {
        "score": 5,
        "why": "96th percentile; 90th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "89th percentile"
      },
      "range": {
        "score": 5,
        "why": "86th percentile"
      },
      "cost": {
        "score": 5,
        "why": "89th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "six plasma cannons in two triple turrets on 546 generators and 96 m of accelerator, plus a laser"
      },
      "aircraft": {
        "score": 3,
        "why": "six plasma cannons on anti-air mantlets and one instant-hit laser; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "four sonar sets find them; nothing reaches under water"
      },
      "missiles": {
        "score": 5,
        "why": "7-node laser point-defence, 22 interceptors, 19 shields, 15 smoke, three jammers, decoys, 10 warners"
      }
    },
    "verdict": "tank",
    "verdictDetail": "Firepower 0.87× and toughness 1.67× the per-material median for its price."
  },
  "LH:Volta": {
    "role": "light laser strike craft",
    "strength": 0,
    "rank": 52,
    "rankTied": true,
    "type": "Light strike skimmer — a quad laser turret on a jet hull; mass-produced, and famously killed by one lucky hit. 36 m long, 25 m wide, 1,092 blocks.",
    "speed": "109.0 m/s (212 kn) — quicker than 19 in 20 ships.",
    "fightsAt": "1,000 m.",
    "sees": "A radar and a radar tracker, a camera and a tracker, two laser rangefinders, a rangefinder, a radio snooper. No warners.",
    "summary": "Cheap laser skimmer. Its own blurb: low cost, moderate damage, hits aircraft, and its captains need \"brass bolts\".",
    "scores": {
      "firepower": {
        "score": 1,
        "why": "19th percentile — all laser"
      },
      "toughness": {
        "score": 1,
        "why": "19th percentile; 43rd among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "86th percentile"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 1,
        "why": "16th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "one quad laser turret on 36 cavities"
      },
      "aircraft": {
        "score": 2,
        "why": "the same turret hits instantly and the blurb says it hits aircraft — but it is small; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 1,
        "why": "two chaff emitters and plating; no warners"
      }
    },
    "verdict": "cheap laser skimmer",
    "verdictDetail": "Firepower 0.81× and toughness 1.00× the per-material median for its price."
  },
  "LH:Watt": {
    "role": "fast escort with decoys",
    "strength": 552,
    "rank": 39,
    "type": "Fast escort skimmer — one laser, six EMP missiles and eleven decoy launchers. 63 m, 2,147 blocks.",
    "speed": "116.3 m/s (226 kn) — quicker than 49 in 50 ships.",
    "fightsAt": "1,000 m.",
    "sees": "One radar and four radar 90s, two camera trackers, three laser rangefinders, a rangefinder, 12 missile warners. No sonar.",
    "summary": "Tough little escort. Twice the toughness of its price class, half the firepower; its job is to draw missiles. Designers: 0.5× vs surface.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "28th percentile — half laser, half missiles"
      },
      "toughness": {
        "score": 3,
        "why": "51st percentile; 82nd among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "89th percentile"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 2,
        "why": "35th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "one laser on 24 cavities and six small missiles that stun rather than sink; designers 0.5×"
      },
      "aircraft": {
        "score": 2,
        "why": "one instant-hit laser and six radar-guided missiles; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "11 decoy launchers, 12 warners, 2 shields; no interceptors"
      }
    },
    "verdict": "tank",
    "verdictDetail": "Firepower 0.54× and toughness 2.25× the per-material median for its price."
  },
  "LH:Cathode": {
    "role": "heavy torpedo submarine with particle pod",
    "strength": 3506,
    "rank": 6,
    "type": "Heavy submarine — six large torpedoes and a four-lens particle pod. 104 m long, 63 m wide, 8,170 blocks including the pod.",
    "speed": "49.0 m/s (95 kn) — quicker than 5 in 6 ships; its designers tell it to cruise.",
    "fightsAt": "1,400 m — longer than 4 in 5 craft.",
    "sees": "Eight active and seven passive sonar sets, 3 laser warners, a radio snooper, and seven radar buoys plus a sonar buoy to float up.",
    "escort": "The pod (\"Strap in or be slapped\", 1,191 blocks): four small particle lenses on 1,375 m of tube.",
    "summary": "Armoured submarine. 4th toughest and 6th strongest Hoods design; designers rate it 1.5× vs surface targets.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "88th percentile — 73 % particle cannon, 27 % torpedoes"
      },
      "toughness": {
        "score": 5,
        "why": "92nd percentile; 73rd among craft of its price"
      },
      "speed": {
        "score": 3,
        "why": "58th percentile; 84th among ships"
      },
      "range": {
        "score": 5,
        "why": "80th percentile"
      },
      "cost": {
        "score": 5,
        "why": "89th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "six large sonar torpedoes (four frag, two EMP) from under water and a four-lens particle pod on 1,375 m of tube; designers 1.5×"
      },
      "aircraft": {
        "score": 2,
        "why": "the particle pod and one warhead-less heat-seeking missile; designers 1×"
      },
      "submarines": {
        "score": 3,
        "why": "fifteen sonar sets and six sonar torpedoes, fighting under water itself — though the designers rate it 0× vs undersea"
      },
      "missiles": {
        "score": 4,
        "why": "submerged, only torpedoes can reach it; 26 torpedo interceptors, 11 shields, 4 smoke, two jammers"
      }
    },
    "verdict": "tank",
    "verdictDetail": "Firepower 0.94× and toughness 1.23× the per-material median for its price, and submerged."
  },
  "LH:Hydrovolt": {
    "role": "armoured torpedo submarine",
    "strength": 1422,
    "rank": 21,
    "type": "Wide, flat submarine — two huge laser-designated torpedoes and a short-range laser turret on a hull that is 37 % heavy armour. 90 m long, 69 m wide, 4,762 blocks.",
    "speed": "55.4 m/s (108 kn) — quicker than 5 in 6 ships.",
    "fightsAt": "1,200 m.",
    "sees": "Seven active and six passive sonar sets, 4 laser warners, a radio snooper — a submarine's fit.",
    "summary": "Armoured submarine with few teeth. Twice the toughness of its price class, 60 % of the firepower. Designers: 20 battle points, difficulty 3.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "51st percentile — 52 % laser, 48 % torpedoes"
      },
      "toughness": {
        "score": 5,
        "why": "80th percentile; 94th among craft of its price"
      },
      "speed": {
        "score": 4,
        "why": "61st percentile; 86th among ships"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 4,
        "why": "64th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "two 14-block torpedoes with four frag warheads, steered onto a laser spot from under water; a six-output short-range laser"
      },
      "aircraft": {
        "score": 2,
        "why": "six short-range lasers on one turret; designers 1×"
      },
      "submarines": {
        "score": 2,
        "why": "thirteen sonar sets, but its two torpedoes follow a laser spot rather than sonar; designers 1×"
      },
      "missiles": {
        "score": 4,
        "why": "submerged, only torpedoes can reach it; 26 torpedo interceptors, 3 shields, 2 smoke generators"
      }
    },
    "verdict": "tank",
    "verdictDetail": "Firepower 0.60× and toughness 2.20× the per-material median for its price, and submerged."
  },
  "LH:Umbra": {
    "role": "missile submarine",
    "strength": 2265,
    "rank": 12,
    "type": "Missile submarine — 32 radar missiles fired downward out of the hull, then up. 91 m long, 29 m wide, 29 m tall, 3,598 blocks.",
    "speed": "28.0 m/s (54 kn) — average for a ship.",
    "fightsAt": "1,000 m.",
    "sees": "Four passive sonar sets and a radio snooper; the missiles carry their own radar.",
    "summary": "Tough missile submarine. 12th strongest Hoods design for 148 k; nothing for submarines or aircraft.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "41st percentile — all missiles"
      },
      "toughness": {
        "score": 4,
        "why": "62nd percentile; 83rd among craft of its price"
      },
      "speed": {
        "score": 2,
        "why": "38th percentile; 58th among ships"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 3,
        "why": "50th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "32 radar-guided missiles with three frag warheads each, launched from under water where guns cannot reach it"
      },
      "aircraft": {
        "score": 2,
        "why": "the missiles can chase aircraft; designers 0.5×"
      },
      "submarines": {
        "score": 1,
        "why": "four passive sonar sets, no torpedoes; missiles cannot reach a submerged target"
      },
      "missiles": {
        "score": 3,
        "why": "submerged, only torpedoes can reach it; 12 torpedo interceptors, two decoy launchers, no shields"
      }
    },
    "verdict": "tank",
    "verdictDetail": "Firepower 0.66× and toughness 1.79× the per-material median for its price; submerged, it is hard to hit at all."
  },
  "LH:Caspian": {
    "role": "sea-skimming torpedo bomber",
    "strength": 2756,
    "rank": 8,
    "type": "Sea-skimming torpedo bomber (the game's aircraft class): a 71 m wing that flies at 14 m with twelve heavy torpedoes. 87 m long, 3,499 blocks.",
    "speed": "110.1 m/s (214 kn) — very fast.",
    "fightsAt": "1,000 m.",
    "sees": "One radar and three radar 90s, two infrared cameras, a camera and a tracker, a retroreflection sensor, 10 missile warners, a radio snooper, and two sonar buoys to drop. No sonar of its own.",
    "summary": "Glass-cannon torpedo bomber. 8th strongest Hoods design; twelve 4-frag-4-EMP torpedoes and 28 shields on an alloy airframe. Designers: 0.3× vs air.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "71st percentile — 72 % torpedoes and missiles, 28 % laser"
      },
      "toughness": {
        "score": 3,
        "why": "49th percentile; 25th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "87th percentile"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 4,
        "why": "61st percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "twelve 10-block sonar torpedoes with 4 frag + 4 EMP warheads each, six large laser-guided EMP missiles, a twin laser"
      },
      "aircraft": {
        "score": 2,
        "why": "a twin laser on a two-axis turret; designers 0.3×"
      },
      "submarines": {
        "score": 2,
        "why": "twelve sonar-seeking torpedoes and two sonar buoys, but no sonar aboard; designers 0×"
      },
      "missiles": {
        "score": 3,
        "why": "28 shields, a 2-node point-defence, heat and radar decoys, 10 warners; no interceptors"
      }
    },
    "verdict": "glass cannon",
    "verdictDetail": "Firepower 1.4× and toughness 0.60× the per-material median for its price."
  },
  "LH:Luxon": {
    "role": "radar glide-bomber",
    "strength": 954,
    "rank": 30,
    "type": "Jet glide-bomber — sixteen radar-guided glide bombs dropped from the tail at 330 knots. 49 m long, 30 m wide, 799 blocks.",
    "speed": "169.7 m/s (330 kn) — quicker than 49 in 50 craft; flies at up to 261 m.",
    "fightsAt": "1,200 m.",
    "sees": "6 missile warners, 4 laser warners and a radio snooper — no radar or camera of its own; it flies on the fleet's picture and the bombs carry their own radar.",
    "summary": "Glide-bomber glass cannon. Twice the firepower of its price class, half the toughness, blind on its own. Designers: 0.3× vs air.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "42nd percentile — all glide bombs"
      },
      "toughness": {
        "score": 1,
        "why": "19th percentile; 25th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "98th percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 2,
        "why": "27th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "twelve radar-guided glide bombs with five frag warheads and four more with 3 EMP + 4 frag"
      },
      "aircraft": {
        "score": 1,
        "why": "glide bombs; designers 0.3×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "six decoy launchers, 6 warners, and speed"
      }
    },
    "verdict": "glass cannon",
    "verdictDetail": "Firepower 1.9× and toughness 0.58× the per-material median for its price."
  },
  "LH:Rectifier": {
    "role": "flying-wing laser and missile carrier",
    "strength": 5514,
    "rank": 3,
    "type": "Flying wing — 106 m across — with sixteen laser turrets and a hundred missiles. 105 m long, 9,011 blocks.",
    "speed": "173.3 m/s (337 kn) — the fastest craft on this list; flies at up to 214 m.",
    "fightsAt": "1,250 m.",
    "sees": "Two radar 90s and four passive radars, eight infrared trackers and six infrared cameras, ten wireless cameras, four cameras, 16 missile warners.",
    "summary": "Flying glass cannon. 3rd strongest Hoods design and the fastest; half the toughness of craft its price and nothing to stop a missile.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "86th percentile — 64 % laser, 36 % missiles"
      },
      "toughness": {
        "score": 4,
        "why": "77th percentile; 12th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "98th percentile"
      },
      "range": {
        "score": 4,
        "why": "72nd percentile"
      },
      "cost": {
        "score": 5,
        "why": "89th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "twenty lasers on 360 cavities and 610 frequency doublers, 96 small and medium missiles, four large EMP/frag missiles"
      },
      "aircraft": {
        "score": 4,
        "why": "48 heat-seeking and 52 radar-guided missiles plus sixteen instant-hit laser turrets at 337 knots; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "16 warners and speed; no interceptors, shields, decoys or point-defence"
      }
    },
    "verdict": "glass cannon",
    "verdictDetail": "Firepower 0.90× and toughness 0.55× the per-material median for its price — everything went into wing, speed and weapons."
  },
  "LH:Dipole": {
    "role": "hover missile picket",
    "strength": 842,
    "rank": 32,
    "type": "Hover missile picket (game class: thruster craft, probable) — twelve missiles on a small metal hull. 48 m long, 39 m wide, 1,244 blocks.",
    "speed": "119.1 m/s (232 kn) — very fast; flies at up to 371 m.",
    "fightsAt": "1,000 m.",
    "sees": "Four radar trackers, cameras with four trackers, two infrared trackers, 2 missile warners, 4 laser warners, a radio snooper.",
    "summary": "Sturdy hover picket. Half again as tough as its price class; twelve EMP-and-frag missiles.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "27th percentile — all missiles"
      },
      "toughness": {
        "score": 3,
        "why": "40th percentile; 68th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "90th percentile"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 2,
        "why": "28th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "twelve radar missiles with an EMP and two frag warheads each"
      },
      "aircraft": {
        "score": 2,
        "why": "the same missiles from a 232-knot craft; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "6 interceptors, 7 smoke, a radar decoy, 2 warners"
      }
    },
    "verdict": "sturdy picket",
    "verdictDetail": "Firepower 0.79× and toughness 1.49× the per-material median for its price."
  },
  "LH:Dynamo": {
    "role": "fast plasma hover-gunboat",
    "strength": 1548,
    "rank": 18,
    "type": "Fast hover-gunboat (game class: thruster craft, probable) — two plasma cannons and a large particle lens fixed forward. 61 m long, 53 m wide, 4,059 blocks.",
    "speed": "147.8 m/s (287 kn) — very fast; flies at up to 115 m.",
    "fightsAt": "1,200 m.",
    "sees": "Two radars and two trackers, five laser rangefinders, infrared cameras and a tracker, cameras, two rangefinders, 8 missile warners, 13 laser warners, a radio snooper.",
    "summary": "Balanced hover-gunboat. Everything points forward and it closes at 287 knots; average numbers for its price.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "74th percentile — 82 % plasma, the rest particle cannon and missiles"
      },
      "toughness": {
        "score": 4,
        "why": "72nd percentile; 50th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "95th percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 4,
        "why": "73rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "two plasma cannons on 306 generators, a large particle lens on 180 m of tube, four EMP missiles"
      },
      "aircraft": {
        "score": 2,
        "why": "fixed forward weapons and four radar missiles; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 3,
        "why": "20 interceptors, 5 shields, 6 smoke, a chaff emitter, 8 warners"
      }
    },
    "verdict": "balanced",
    "verdictDetail": "Firepower 1.09× and toughness 0.98× the per-material median for its price."
  },
  "LH:Faraday": {
    "role": "plasma hover-boat with torpedoes",
    "strength": 1511,
    "rank": 19,
    "type": "Hover-boat (game class: thruster craft, probable) with two plasma cannons, ten EMP missiles and two torpedoes. 44 m long, 35 m wide, 1,880 blocks.",
    "speed": "81.3 m/s (158 kn) — fast; flies at up to 179 m.",
    "fightsAt": "1,000 m.",
    "sees": "Three radar 90s, two radar trackers and a passive radar, cameras, infrared cameras, two laser rangefinders, a rangefinder, 11 missile warners, a radio snooper. No sonar.",
    "summary": "Leans glass. A third more firepower than its price class, 60 % of the toughness.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "55th percentile — 55 % plasma, 45 % missiles"
      },
      "toughness": {
        "score": 2,
        "why": "37th percentile; 30th among craft of its price"
      },
      "speed": {
        "score": 4,
        "why": "75th percentile"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 3,
        "why": "49th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "two plasma cannons, six EMP-and-frag and four EMP missiles, two sonar torpedoes"
      },
      "aircraft": {
        "score": 2,
        "why": "fixed plasma mantlets and ten radar-guided missiles; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "two sonar torpedoes but no sonar to find a target with"
      },
      "missiles": {
        "score": 2,
        "why": "9 interceptors, 2 shields, 2 smoke, chaff, a jammer, 11 warners"
      }
    },
    "verdict": "leans glass cannon",
    "verdictDetail": "Firepower 1.29× and toughness 0.61× the per-material median for its price."
  },
  "LH:Quadrupole": {
    "role": "flying plasma battleship",
    "strength": 6451,
    "rank": 2,
    "type": "Flying plasma battleship (game class: thruster craft, probable) — one huge plasma cannon, 27 missiles, two particle turrets. 91 m long, 49 m wide, 28 m tall, 6,754 blocks.",
    "speed": "131.7 m/s (256 kn) — very fast; flies at up to 206 m.",
    "fightsAt": "1,250 m.",
    "sees": "Six radar trackers, cameras with four trackers, three infrared cameras, three rangefinders, 11 missile warners, 14 laser warners. No all-round radar.",
    "summary": "Flying heavyweight, leans glass. 2nd strongest and 2nd hardest-hitting Hoods design; 80 % the toughness of craft its price.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "94th percentile — 62 % plasma, 35 % missiles"
      },
      "toughness": {
        "score": 5,
        "why": "84th percentile; 38th among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "93rd percentile"
      },
      "range": {
        "score": 4,
        "why": "72nd percentile"
      },
      "cost": {
        "score": 5,
        "why": "88th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "one plasma cannon on 560 generators and 140 m of chambers, twelve large radar frag missiles, fifteen EMP missiles"
      },
      "aircraft": {
        "score": 3,
        "why": "27 radar- and heat-guided missiles from a 256-knot platform; the plasma cannon is fixed forward; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 3,
        "why": "12 interceptors, 14 shields, 5 smoke, 11 warners"
      }
    },
    "verdict": "leans glass cannon",
    "verdictDetail": "Firepower 1.41× and toughness 0.82× the per-material median for its price."
  }
}
