// GENERATED by scripts/import-ship-profiles.ts from SS.cards.md — do not hand-edit.
// Re-run the importer on a fresh report instead; shared/shipProfiles.test.ts pins
// every key here to a seeded card.
import type { ShipProfile } from '../shipProfiles.ts'

export const SS_SHIP_PROFILES: Record<string, ShipProfile> = {
  "SS:Sacrilego": {
    "role": "armed cargo ship",
    "strength": 365,
    "rank": 74,
    "type": "Armed cargo ship (the game tags it \"Cargo Ship\"). 120 m, 4,698 blocks.",
    "speed": "26.5 m/s (52 kn).",
    "fightsAt": "1,200 m.",
    "sees": "Four radars and a radio snooper. No sonar, cameras or missile warners.",
    "summary": "Freighter, not a warship. A tough hull that can barely shoot back. Designers: 10 battle points, difficulty 1.",
    "scores": {
      "firepower": {
        "score": 1,
        "why": "19th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "62nd percentile — 3.5× the per-material median for its price"
      },
      "speed": {
        "score": 2,
        "why": "36th percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 2,
        "why": "34th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 1,
        "why": "two small heat-seeking missiles; designers 0.2×"
      },
      "aircraft": {
        "score": 1,
        "why": "four light 40 mm AA mounts; designers 0.2×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 1,
        "why": "one radar decoy and one smoke; no warners"
      }
    },
    "verdict": "freighter",
    "verdictDetail": "Firepower 0.32× and toughness 3.5× the per-material medians for its price."
  },
  "SS:Resolute": {
    "role": "destroyer escort",
    "strength": 482,
    "rank": 69,
    "type": "Destroyer escort. 102 m, 2,560 blocks.",
    "speed": "38.5 m/s (75 kn) — quick; faster than 3 in 4 ships.",
    "fightsAt": "1,000 m.",
    "sees": "Five radars (two tracking), two laser rangefinders, a camera tracker, passive sonar. No missile warners.",
    "summary": "Sturdy little escort. Airburst guns, three torpedoes, a lot of plating for the price.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "27th percentile"
      },
      "toughness": {
        "score": 3,
        "why": "45th percentile — 2.2× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "50th percentile"
      },
      "range": {
        "score": 2,
        "why": "33rd percentile"
      },
      "cost": {
        "score": 2,
        "why": "28th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "four 120 mm airburst guns, three torpedoes"
      },
      "aircraft": {
        "score": 2,
        "why": "gun-only: the 120 mm guns on anti-air mounts and four twin 40 mm"
      },
      "submarines": {
        "score": 2,
        "why": "three sonar torpedoes, passive sonar"
      },
      "missiles": {
        "score": 1,
        "why": "two smoke generators, nothing else"
      }
    },
    "verdict": "sturdy escort",
    "verdictDetail": "Firepower 0.77× and toughness 2.2× the per-material medians for its price."
  },
  "SS:Chrysaor": {
    "role": "fast attack boat",
    "strength": 573,
    "rank": 65,
    "type": "Fast attack boat that closes at 90 m/s to burn and shoot. 53 m, 2,145 blocks.",
    "speed": "90 m/s (175 kn) — faster than 9 in 10 ships.",
    "fightsAt": "1,000 m.",
    "sees": "One radar, a camera, a laser rangefinder, 11 missile warners and 3 laser warners. No sonar.",
    "summary": "Fast brawler. The game rates its under-hull flamethrower as 89 % of its firepower.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "63rd percentile — mostly the flamethrower"
      },
      "toughness": {
        "score": 3,
        "why": "51st percentile — 1.4× the per-material median for its price"
      },
      "speed": {
        "score": 4,
        "why": "79th percentile"
      },
      "range": {
        "score": 2,
        "why": "33rd percentile"
      },
      "cost": {
        "score": 3,
        "why": "43rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "eight radar missiles and a flamethrower it must bring to point-blank"
      },
      "aircraft": {
        "score": 2,
        "why": "the eight missiles can chase aircraft; designers 0.3×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 3,
        "why": "6 interceptors, 7 shields, 11 warners, 5 smoke dispensers"
      }
    },
    "verdict": "fast brawler",
    "verdictDetail": "Firepower 2.1× and toughness 1.4× the per-material medians for its price — a bargain if it survives the run in."
  },
  "SS:Falcon Squadron": {
    "role": "three jet fighters",
    "strength": 472,
    "rank": 70,
    "type": "A squadron of three jet fighters, 453 blocks each (34 m long).",
    "speed": "161 m/s (313 kn) — the fastest craft on this list; flies at up to 444 m.",
    "fightsAt": "1,200 m.",
    "sees": "Per jet: a laser rangefinder, a camera, 5 warners, a radio snooper. No radar — the missiles find their own targets.",
    "note": "Firepower and toughness below are for one jet (the game rates each craft on its own); cost is for the squadron.",
    "summary": "Glass-cannon fighters. EMP missiles and HEAT cannons on paper-thin airframes. Designers: 12 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "39th percentile — per jet"
      },
      "toughness": {
        "score": 1,
        "why": "10th percentile — 7.7 M armoured health per jet"
      },
      "speed": {
        "score": 5,
        "why": "98th percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 2,
        "why": "37th percentile (the squadron)"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "18 missiles across the squadron, half carrying EMP; HEAT cannons"
      },
      "aircraft": {
        "score": 3,
        "why": "fighters: 161 m/s, radar and heat-seeking missiles, cannons on all-round mounts"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "two flare launchers per jet, and speed"
      }
    },
    "verdict": "glass-cannon fighters",
    "verdictDetail": "Per jet, firepower 1.0× and toughness 0.13× the per-material medians for its price."
  },
  "SS:Argonaut": {
    "role": "gun destroyer",
    "strength": 531,
    "rank": 66,
    "type": "Gun destroyer. 126 m, 3,995 blocks.",
    "speed": "31.5 m/s (61 kn).",
    "fightsAt": "1,300 m.",
    "sees": "Ten radars (four tracking), cameras, two rangefinders. No sonar, no missile warners.",
    "summary": "Tough gun destroyer. Hard to kill, hits softly.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "28th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "60th percentile — 2.5× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "42nd percentile"
      },
      "range": {
        "score": 4,
        "why": "76th percentile"
      },
      "cost": {
        "score": 2,
        "why": "37th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "ten 150 mm airburst guns — light"
      },
      "aircraft": {
        "score": 2,
        "why": "gun-only; designers 0.4×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 1,
        "why": "two smoke generators; no warners"
      }
    },
    "verdict": "tough, hits softly",
    "verdictDetail": "Firepower 0.52× and toughness 2.5× the per-material medians for its price."
  },
  "SS:Catshark": {
    "role": "fast frigate",
    "strength": 1098,
    "rank": 56,
    "type": "Fast frigate with EMP torpedoes and a laser point-defence. 68 m, 2,148 blocks.",
    "speed": "37.1 m/s (72 kn) — faster than 3 in 4 ships.",
    "fightsAt": "1,000 m.",
    "sees": "Three laser rangefinders, two cameras, a sonar and a passive sonar, 7 warners. No radar.",
    "summary": "Balanced frigate. Average in every ratio; its torpedoes stun rather than sink. Designers: 10 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "43rd percentile"
      },
      "toughness": {
        "score": 3,
        "why": "44th percentile — 1.02× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "49th percentile"
      },
      "range": {
        "score": 2,
        "why": "33rd percentile"
      },
      "cost": {
        "score": 3,
        "why": "44th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "seven torpedoes (four EMP), a 200 mm gun, four frag-cluster missiles"
      },
      "aircraft": {
        "score": 2,
        "why": "two guns on anti-air mounts, four small radar missiles; designers 0.6×"
      },
      "submarines": {
        "score": 3,
        "why": "seven sonar torpedoes and two sonar sets; designers 1.0×"
      },
      "missiles": {
        "score": 3,
        "why": "laser point-defence, 11 shields, 7 warners; no interceptors"
      }
    },
    "verdict": "balanced",
    "verdictDetail": "Firepower 0.93× and toughness 1.02× the per-material medians for its price."
  },
  "SS:PredatorX": {
    "role": "jet fighter",
    "strength": 1570,
    "rank": 46,
    "type": "Jet fighter. 46 m long, 45 m wingspan, 1,742 blocks.",
    "speed": "149 m/s (290 kn); flies at up to 425 m.",
    "fightsAt": "1,400 m.",
    "sees": "Five radars, a camera tracker, 11 warners.",
    "summary": "Fighter, leans glass. Twin cannons and twelve EMP missiles; a pair of them beats a Crossbones. Designers: 20 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "47th percentile"
      },
      "toughness": {
        "score": 2,
        "why": "30th percentile — 0.47× the per-material median for its price"
      },
      "speed": {
        "score": 5,
        "why": "96th percentile"
      },
      "range": {
        "score": 5,
        "why": "81st percentile"
      },
      "cost": {
        "score": 3,
        "why": "47th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "twelve radar-guided EMP/frag missiles, twin 180 mm cannons"
      },
      "aircraft": {
        "score": 3,
        "why": "fighter: 149 m/s, twin cannons on an anti-air mount, radar and heat-seeking missiles"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 3,
        "why": "4 interceptors, 10 shields, 11 warners, flares"
      }
    },
    "verdict": "leans glass cannon",
    "verdictDetail": "Firepower 1.0× and toughness 0.47× the per-material medians for its price."
  },
  "SS:Typhoon": {
    "role": "missile submarine",
    "strength": 2071,
    "rank": 39,
    "type": "Missile submarine — a low-profile boat that runs under the radar and under the water. 79 m, 2,527 blocks.",
    "speed": "38.8 m/s (75 kn) — faster than 3 in 4 ships.",
    "fightsAt": "1,200 m.",
    "sees": "Six sonar sets and a radio snooper — a submarine's fit; no radar or cameras. The missiles carry their own radar.",
    "summary": "Missile submarine. Thirty radar missiles and six heavy torpedoes fired from under the surface; shields against shells, the sea against most missiles. Designers: 32 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "39th percentile"
      },
      "toughness": {
        "score": 3,
        "why": "57th percentile — 1.5× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "50th percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 3,
        "why": "46th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "30 radar-guided missiles and six heavy torpedoes, launched from under water where guns cannot reach it"
      },
      "aircraft": {
        "score": 2,
        "why": "the missiles can chase aircraft; designers 0.5×"
      },
      "submarines": {
        "score": 3,
        "why": "six sonar torpedoes, six sonar sets, and it fights under water itself; designers 0.5×"
      },
      "missiles": {
        "score": 3,
        "why": "submerged, only torpedoes can reach it; 18 shields, but no interceptors, warners or decoys"
      }
    },
    "verdict": "missile submarine",
    "verdictDetail": "Firepower 0.68× and toughness 1.5× the per-material medians for its price; submerged, it is hard to hit at all."
  },
  "SS:Iron Maiden": {
    "role": "gun cruiser",
    "strength": 1320,
    "rank": 50,
    "type": "\"All guns forward\" cruiser — the design that grew into the Tyr. 129 m, 5,394 blocks.",
    "speed": "28.3 m/s (55 kn).",
    "fightsAt": "1,400 m.",
    "sees": "Five radars (three tracking), two telescope trackers, a sonar, 11 warners, four rangefinders.",
    "summary": "Tough gun cruiser. Four armour-piercing 360 mm guns, all forward. Designers: 40 battle points.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "47th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "70th percentile — 2.2× the per-material median for its price"
      },
      "speed": {
        "score": 2,
        "why": "39th percentile"
      },
      "range": {
        "score": 5,
        "why": "81st percentile"
      },
      "cost": {
        "score": 3,
        "why": "53rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "four 360 mm armour-piercing guns, six torpedoes"
      },
      "aircraft": {
        "score": 2,
        "why": "one 60 mm close-in gun, two heat-seeking missiles; designers 0.5×"
      },
      "submarines": {
        "score": 2,
        "why": "six sonar torpedoes, one sonar; designers 0.2×"
      },
      "missiles": {
        "score": 2,
        "why": "one close-in gun, 11 warners, smoke"
      }
    },
    "verdict": "tough gun cruiser",
    "verdictDetail": "Firepower 0.80× and toughness 2.2× the per-material medians for its price."
  },
  "SS:Spectre": {
    "role": "stealth missile ship",
    "strength": 3400,
    "rank": 30,
    "type": "Stealth electronic-warfare missile ship — passive sensors, chaff, EMP, mines. 104 m, 4,441 blocks.",
    "speed": "33.2 m/s (65 kn).",
    "fightsAt": "1,200 m.",
    "sees": "Passive radars plus one tracking radar, a retroreflection sensor (spots enemy optics), passive sonar, 10 warners — it listens rather than emits.",
    "summary": "Balanced EMP specialist. Torpedoes, missiles and mines, with chaff and smoke to hide behind. Designers: 20 battle points, difficulty 3.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "64th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "65th percentile — 1.26× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "44th percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 3,
        "why": "59th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "ten torpedoes, 18 radar missiles (six EMP), five mines"
      },
      "aircraft": {
        "score": 3,
        "why": "18 radar-guided missiles; designers 1.4×"
      },
      "submarines": {
        "score": 3,
        "why": "ten sonar torpedoes, passive sonar; designers 1.0×"
      },
      "missiles": {
        "score": 4,
        "why": "10 interceptors, 4 chaff emitters, 8 smoke, 2 flares, 10 warners"
      }
    },
    "verdict": "balanced",
    "verdictDetail": "Firepower 1.12× and toughness 1.26× the per-material medians for its price."
  },
  "SS:Hydra": {
    "role": "VTOL missile gunship",
    "strength": 2981,
    "rank": 31,
    "type": "VTOL missile gunship on lift turbines; flies at up to 308 m. 71 m long, 33 m wide, 3,154 blocks.",
    "speed": "62.8 m/s (122 kn).",
    "fightsAt": "1,000 m.",
    "sees": "Two passive radars, two laser rangefinders, an infrared tracker, cameras, 14 warners. No sonar.",
    "summary": "Flying missile gunship, leans glass. Sixteen radar missiles and one big gun. Designers: 25 battle points, difficulty 1.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "69th percentile"
      },
      "toughness": {
        "score": 3,
        "why": "55th percentile — 0.69× the per-material median for its price"
      },
      "speed": {
        "score": 4,
        "why": "66th percentile"
      },
      "range": {
        "score": 2,
        "why": "33rd percentile"
      },
      "cost": {
        "score": 4,
        "why": "63rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "four large, six EMP and six small radar missiles, plus the gun"
      },
      "aircraft": {
        "score": 3,
        "why": "sixteen radar-guided missiles, a gun on an anti-air mount, and it flies"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 4,
        "why": "14 interceptors, 8 flare launchers, 14 warners, 3 shields"
      }
    },
    "verdict": "leans glass cannon",
    "verdictDetail": "Firepower 1.26× and toughness 0.69× the per-material medians for its price."
  },
  "SS:Maelstrom": {
    "role": "jet torpedo bomber",
    "strength": 2633,
    "rank": 35,
    "type": "Jet bomber that drops torpedoes and EMP mines; flies at up to 344 m. 79 m long, 45 m wide, 2,817 blocks.",
    "speed": "149 m/s (290 kn).",
    "fightsAt": "1,300 m.",
    "sees": "Five radars, a camera, 8 warners. No sonar.",
    "summary": "Fast torpedo bomber. Built to hunt ships and submarines; useless against aircraft. Designers: 18 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "51st percentile"
      },
      "toughness": {
        "score": 3,
        "why": "53rd percentile — 0.67× the per-material median for its price"
      },
      "speed": {
        "score": 5,
        "why": "96th percentile"
      },
      "range": {
        "score": 4,
        "why": "76th percentile"
      },
      "cost": {
        "score": 4,
        "why": "62nd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "six heavy torpedoes, 16 mines, 14 radar/EMP missiles, 16 heat-seekers"
      },
      "aircraft": {
        "score": 1,
        "why": "designers 0×"
      },
      "submarines": {
        "score": 3,
        "why": "six sonar torpedoes and EMP mines; designers 1.2× — its intended prey"
      },
      "missiles": {
        "score": 4,
        "why": "laser point-defence, 23 shields, 4 interceptors, chaff, 8 warners"
      }
    },
    "verdict": "fast, pricey",
    "verdictDetail": "Firepower 0.65× and toughness 0.67× the per-material medians for its price — you pay for the speed and the laser."
  },
  "SS:Paladin": {
    "role": "armoured gun-line ship",
    "strength": 1632,
    "rank": 44,
    "type": "Old-style armoured gun-line ship with casemate guns. 162 m, 8,505 blocks.",
    "speed": "20.8 m/s (40 kn) — slow.",
    "fightsAt": "1,300 m.",
    "sees": "Fifteen radars (two tracking), cameras, two infrared trackers, 16 warners, four rangefinders. No sonar.",
    "summary": "Tank. 214 armour plates around nine 300 mm guns; blind under water and near-blind to the sky.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "51st percentile"
      },
      "toughness": {
        "score": 4,
        "why": "78th percentile — 2.1× the per-material median for its price"
      },
      "speed": {
        "score": 2,
        "why": "30th percentile"
      },
      "range": {
        "score": 4,
        "why": "76th percentile"
      },
      "cost": {
        "score": 4,
        "why": "63rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "nine 300 mm guns, twenty 130 mm casemates"
      },
      "aircraft": {
        "score": 1,
        "why": "six quad 40 mm mounts; designers 0.2×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "six anti-missile controllers on the light guns, 16 warners, 2 smoke"
      }
    },
    "verdict": "tank",
    "verdictDetail": "Firepower 0.61× and toughness 2.1× the per-material medians for its price."
  },
  "SS:Victoria": {
    "role": "gun battleship",
    "strength": 2150,
    "rank": 38,
    "type": "Gun battleship — the navy's standard 360 mm turret ship. 158 m, 7,292 blocks.",
    "speed": "28.9 m/s (56 kn).",
    "fightsAt": "1,500 m.",
    "sees": "Seven radars (four tracking), four telescope trackers, passive sonar, 15 warners, seven rangefinders.",
    "summary": "Tank-brawler. Eight armour-piercing 360 mm guns behind 158 armour plates.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "60th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "76th percentile — 1.7× the per-material median for its price"
      },
      "speed": {
        "score": 2,
        "why": "39th percentile"
      },
      "range": {
        "score": 5,
        "why": "87th percentile"
      },
      "cost": {
        "score": 4,
        "why": "66th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "eight 360 mm armour-piercing guns"
      },
      "aircraft": {
        "score": 2,
        "why": "four close-in guns, six light AA mounts, four heat-seekers — gun-only"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 3,
        "why": "four close-in guns with controllers, 15 warners, 2 smoke"
      }
    },
    "verdict": "tank-brawler",
    "verdictDetail": "Firepower 0.79× and toughness 1.7× the per-material medians for its price."
  },
  "SS:Wolin": {
    "role": "missile submarine",
    "strength": 4565,
    "rank": 26,
    "type": "Missile submarine carrying four enormous torpedoes. 97 m, 3,689 blocks.",
    "speed": "29.9 m/s (58 kn).",
    "fightsAt": "1,500 m.",
    "sees": "Six sonar sets, six laser warners, a radio snooper — a submarine's fit; no radar, cameras or missile warners.",
    "summary": "Balanced missile submarine. Forty-eight radar missiles and 21-block torpedoes, launched from under the surface.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "70th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "68th percentile — 1.06× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "40th percentile"
      },
      "range": {
        "score": 5,
        "why": "87th percentile"
      },
      "cost": {
        "score": 4,
        "why": "67th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "48 radar-guided missiles and four giant torpedoes, from under water"
      },
      "aircraft": {
        "score": 3,
        "why": "48 radar-guided missiles; designers 0.8×"
      },
      "submarines": {
        "score": 3,
        "why": "four heavy torpedoes, six sonar sets, and it fights under water itself; designers 0.8×"
      },
      "missiles": {
        "score": 4,
        "why": "submerged, only torpedoes can reach it; 12 interceptors, a close-in gun, 18 smoke dispensers"
      }
    },
    "verdict": "balanced missile submarine",
    "verdictDetail": "Firepower 1.10× and toughness 1.06× the per-material medians for its price; submerged, it is hard to hit at all."
  },
  "SS:Cyclone": {
    "role": "torpedo submarine",
    "strength": 3735,
    "rank": 29,
    "type": "Armoured torpedo submarine with a particle cannon. 120 m, 4,105 blocks.",
    "speed": "26.2 m/s (51 kn).",
    "fightsAt": "1,400 m.",
    "sees": "Seven sonar sets and a radio snooper — a submarine's fit; no radar, cameras or missile warners.",
    "summary": "Armoured sub-hunter. Twenty torpedoes, a particle cannon and 267 armour plates; nothing for the sky.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "69th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "72nd percentile — 1.28× the per-material median for its price"
      },
      "speed": {
        "score": 2,
        "why": "36th percentile"
      },
      "range": {
        "score": 5,
        "why": "81st percentile"
      },
      "cost": {
        "score": 4,
        "why": "68th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "20 torpedoes, four large radar missiles and a particle cannon, from under water"
      },
      "aircraft": {
        "score": 1,
        "why": "four small missiles and one 80 mm gun; designers 0.2×"
      },
      "submarines": {
        "score": 4,
        "why": "20 sonar torpedoes, seven sonar sets, and it fights under water itself"
      },
      "missiles": {
        "score": 4,
        "why": "submerged, only torpedoes can reach it; 8 interceptors, 12 shields"
      }
    },
    "verdict": "armoured torpedo submarine",
    "verdictDetail": "Firepower 1.00× and toughness 1.28× the per-material medians for its price; submerged, it is hard to hit at all."
  },
  "SS:Braveheart": {
    "role": "missile/railgun cruiser",
    "strength": 5353,
    "rank": 23,
    "type": "All-round missile-and-railgun cruiser. 131 m, 6,600 blocks.",
    "speed": "25.3 m/s (49 kn).",
    "fightsAt": "1,150 m.",
    "sees": "Three radars (one tracking), four sonar sets, a laser rangefinder, cameras, 6 warners and 3 laser warners.",
    "summary": "Brawler. Torpedoes, heavy missiles, railguns and anti-air missiles — a bit of everything, well armoured.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "81st percentile"
      },
      "toughness": {
        "score": 4,
        "why": "74th percentile — 1.03× the per-material median for its price"
      },
      "speed": {
        "score": 2,
        "why": "35th percentile"
      },
      "range": {
        "score": 4,
        "why": "62nd percentile"
      },
      "cost": {
        "score": 4,
        "why": "75th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "twelve torpedoes (eight heavy), eight heavy missiles, three railguns"
      },
      "aircraft": {
        "score": 3,
        "why": "eight heat-seeking anti-air missiles on turrets, a close-in gun"
      },
      "submarines": {
        "score": 3,
        "why": "twelve torpedoes, four sonar sets; designers 1.0×"
      },
      "missiles": {
        "score": 4,
        "why": "8 interceptors, 8 decoys, 14 shields, 15 smoke dispensers, close-in gun"
      }
    },
    "verdict": "brawler",
    "verdictDetail": "Firepower 1.36× and toughness 1.03× the per-material medians for its price."
  },
  "SS:Trondheim": {
    "role": "CRAM battleship",
    "strength": 3865,
    "rank": 28,
    "type": "CRAM battleship with fortress-grade missile defence. 182 m, 9,881 blocks.",
    "speed": "34.4 m/s (67 kn).",
    "fightsAt": "1,050 m.",
    "sees": "Ten radars, three laser rangefinders, infrared and camera trackers, passive sonar, 11 warners and 7 laser warners.",
    "summary": "Tank, missile-proof. Nine CRAM guns, 35 shields, 20 interceptors; helpless against aircraft. Designers: 30 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "76th percentile"
      },
      "toughness": {
        "score": 5,
        "why": "81st percentile — 1.30× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "46th percentile"
      },
      "range": {
        "score": 3,
        "why": "58th percentile"
      },
      "cost": {
        "score": 4,
        "why": "76th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "nine CRAM guns, six torpedoes, five missiles"
      },
      "aircraft": {
        "score": 1,
        "why": "CRAM cannot track aircraft; three close-in guns and five light mounts; designers 0.2×"
      },
      "submarines": {
        "score": 2,
        "why": "six sonar torpedoes, passive sonar; designers 0.1×"
      },
      "missiles": {
        "score": 5,
        "why": "20 interceptors, 35 shields, three close-in guns with 14 controllers, 41 smoke dispensers, chaff and decoys"
      }
    },
    "verdict": "tank",
    "verdictDetail": "Firepower 1.04× and toughness 1.30× the per-material medians for its price, plus the missile defence of a fortress."
  },
  "SS:Asphodel": {
    "role": "missile battleship",
    "strength": 9221,
    "rank": 8,
    "type": "Missile battleship behind a wall of point defence. 174 m, 8,507 blocks.",
    "speed": "43.1 m/s (84 kn) — faster than 4 in 5 ships.",
    "fightsAt": "1,500 m.",
    "sees": "22 radars (18 tracking), 12 laser rangefinders, 7 infrared trackers, 5 sonar sets, 31 warners and 20 laser warners — the best-sighted craft on this list.",
    "escort": "The Penguin (298 blocks): two heat-seeking missiles, two large torpedoes, a mine, a flare launcher.",
    "summary": "Point-defence fortress. Twenty-six large missiles, 51 shields, 46 interceptors. Designers: 32 battle points, difficulty 3.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "82nd percentile"
      },
      "toughness": {
        "score": 5,
        "why": "82nd percentile — 0.94× the per-material median for its price (shields not counted)"
      },
      "speed": {
        "score": 3,
        "why": "54th percentile"
      },
      "range": {
        "score": 5,
        "why": "87th percentile"
      },
      "cost": {
        "score": 5,
        "why": "83rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "26 large guided missiles, eight of them shaped-charge; the Penguin's torpedoes"
      },
      "aircraft": {
        "score": 2,
        "why": "the large missiles take 11 s to spool up — not for aircraft; one close-in flak gun"
      },
      "submarines": {
        "score": 2,
        "why": "the Penguin's two sonar torpedoes, five sonar sets; designers 0.5×"
      },
      "missiles": {
        "score": 5,
        "why": "46 interceptors, 51 shields, close-in flak, 2 chaff, decoys, 31 warners"
      }
    },
    "verdict": "point-defence fortress",
    "verdictDetail": "Firepower 0.98× and toughness 0.94× the per-material medians for its price — average per material, but 51 shields and 46 interceptors make it very hard to hit."
  },
  "SS:Nothung": {
    "role": "heavy gun cruiser",
    "strength": 5580,
    "rank": 22,
    "type": "Armoured heavy gun cruiser with quad 440 mm turrets. 184 m, 11,383 blocks.",
    "speed": "39.5 m/s (77 kn).",
    "fightsAt": "1,000 m — short for its guns.",
    "sees": "Ten radars (two tracking), six sonar sets, laser and infrared trackers, 13 warners and 12 laser warners.",
    "escort": "Ink-Eye MkII, a 32-block drone.",
    "summary": "Tank-brawler. Eight armour-piercing 440 mm guns and 32 interceptors.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "72nd percentile"
      },
      "toughness": {
        "score": 5,
        "why": "87th percentile — 1.45× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "51st percentile"
      },
      "range": {
        "score": 2,
        "why": "33rd percentile"
      },
      "cost": {
        "score": 5,
        "why": "80th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "eight 440 mm armour-piercing guns with 23 m barrels"
      },
      "aircraft": {
        "score": 3,
        "why": "fourteen heat-seeking missiles, two close-in flak guns"
      },
      "submarines": {
        "score": 1,
        "why": "no torpedoes"
      },
      "missiles": {
        "score": 5,
        "why": "32 interceptors, 14 shields, two flak guns with 7 controllers, 6 heat decoys, 13 smoke"
      }
    },
    "verdict": "tank-brawler",
    "verdictDetail": "Firepower 0.72× and toughness 1.45× the per-material medians for its price."
  },
  "SS:Mobula": {
    "role": "flying-wing cruiser",
    "strength": 6380,
    "rank": 14,
    "type": "Top-secret flying-wing airborne cruiser with a particle cannon; flies at up to 412 m. 72 m long, 165 m wingspan, 7,328 blocks.",
    "speed": "115 m/s (224 kn).",
    "fightsAt": "1,200 m.",
    "sees": "Five radars, infrared cameras and two infrared trackers, a retroreflection sensor, 16 warners and 6 laser warners. No sonar.",
    "summary": "Flying glass cannon. A particle cannon, sixty missiles and eight torpedoes on a thin airframe kept alive by 44 shields and lasers. Designers: 42 battle points, difficulty 3.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "88th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "63rd percentile — 0.34× the per-material median for its price"
      },
      "speed": {
        "score": 5,
        "why": "89th percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 5,
        "why": "86th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "particle cannon, 60 radar-guided missiles, eight heavy torpedoes dropped from the air"
      },
      "aircraft": {
        "score": 3,
        "why": "60 radar-guided missiles, eight heat-seekers; designers 0.7×"
      },
      "submarines": {
        "score": 2,
        "why": "eight heavy sonar torpedoes, but no sonar to find a submarine with"
      },
      "missiles": {
        "score": 5,
        "why": "laser point-defence with 17 nodes, 44 shields, 6 interceptors, 16 warners, smoke, decoys"
      }
    },
    "verdict": "flying glass cannon",
    "verdictDetail": "Firepower 1.14× and toughness 0.34× the per-material medians for its price — shields and lasers keep it alive, not the hull."
  },
  "SS:Excalibur": {
    "role": "big-gun battleship",
    "strength": 6173,
    "rank": 16,
    "type": "Big-gun battleship: four quad turrets of ~500 mm guns. 185 m, 15,535 blocks.",
    "speed": "26.2 m/s (51 kn).",
    "fightsAt": "2,000 m — the longest reach on this list, shared with the Tyr.",
    "sees": "Thirteen radars (two tracking), telescope and infrared trackers, passive sonar, 5 warners and 10 laser warners, seven rangefinders.",
    "summary": "Big-gun tank. Built \"to pound the strongest armour to dust\"; helpless against aircraft. Designers: 50 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "85th percentile"
      },
      "toughness": {
        "score": 5,
        "why": "90th percentile — 1.48× the per-material median for its price"
      },
      "speed": {
        "score": 2,
        "why": "36th percentile"
      },
      "range": {
        "score": 5,
        "why": "98th percentile"
      },
      "cost": {
        "score": 5,
        "why": "83rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "sixteen ~500 mm HE guns, four heavy torpedoes"
      },
      "aircraft": {
        "score": 1,
        "why": "six 200 mm airburst guns and 14 light AA mounts; designers 0.1×"
      },
      "submarines": {
        "score": 2,
        "why": "four sonar torpedoes, passive sonar; designers 0.1×"
      },
      "missiles": {
        "score": 2,
        "why": "no interceptors, no shields; six CIWS controllers on the AA guns, 5 warners, smoke"
      }
    },
    "verdict": "big-gun tank",
    "verdictDetail": "Firepower 1.16× and toughness 1.48× the per-material medians for its price."
  },
  "SS:Thresher Shark": {
    "role": "sniper cruiser",
    "strength": 7050,
    "rank": 12,
    "type": "Long-gun sniper cruiser with a laser point-defence. 108 m, 9,198 blocks.",
    "speed": "40.3 m/s (78 kn).",
    "fightsAt": "1,600 m.",
    "sees": "Three radars (two tracking), a retroreflection sensor, passive sonar, cameras, 9 warners.",
    "summary": "Sniper glass cannon. Twin guns with 39 m barrels on a hull that cannot take a hit for its price. Designers: 45 battle points, difficulty 3; 2× vs surface targets.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "96th percentile — 4th highest in the faction"
      },
      "toughness": {
        "score": 4,
        "why": "79th percentile — and only 0.51× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "51st percentile"
      },
      "range": {
        "score": 5,
        "why": "92nd percentile"
      },
      "cost": {
        "score": 5,
        "why": "93rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "twin 39 m sniper guns, eleven torpedoes, six heavy missiles; designers 2.0×"
      },
      "aircraft": {
        "score": 2,
        "why": "six radar missiles, one 80 mm gun; designers 0.5×"
      },
      "submarines": {
        "score": 2,
        "why": "eleven sonar torpedoes, passive sonar only; designers 0.2×"
      },
      "missiles": {
        "score": 4,
        "why": "16 interceptors, laser point-defence with 10 nodes, 9 warners, decoys; only 4 shields"
      }
    },
    "verdict": "sniper glass cannon",
    "verdictDetail": "Firepower 1.27× and toughness 0.51× the per-material medians for its price."
  },
  "SS:Balmung": {
    "role": "fast gun battleship",
    "strength": 4838,
    "rank": 25,
    "type": "Fast armoured gun battleship. 181 m, 11,351 blocks.",
    "speed": "50.3 m/s (98 kn) — faster than 5 in 6 ships.",
    "fightsAt": "1,000 m — short for its guns.",
    "sees": "Sixteen radars (eight tracking), ten laser rangefinders, eleven camera and infrared trackers, passive sonar, 17 warners and 9 laser warners.",
    "escort": "Ink-Eye MkII, a 32-block drone.",
    "summary": "Tank-brawler. Ten armour-piercing 322 mm guns with 21 m barrels; quick for a battleship.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "86th percentile"
      },
      "toughness": {
        "score": 5,
        "why": "90th percentile — 1.23× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "59th percentile"
      },
      "range": {
        "score": 2,
        "why": "33rd percentile"
      },
      "cost": {
        "score": 5,
        "why": "86th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "ten 322 mm armour-piercing guns"
      },
      "aircraft": {
        "score": 2,
        "why": "the main guns sit on anti-air mounts, plus three close-in guns and four heat-seekers — gun-only"
      },
      "submarines": {
        "score": 1,
        "why": "no torpedoes"
      },
      "missiles": {
        "score": 4,
        "why": "16 interceptors, 15 shields, three close-in guns with 4 controllers, 16 smoke, 17 warners"
      }
    },
    "verdict": "tank-brawler",
    "verdictDetail": "Firepower 1.03× and toughness 1.23× the per-material medians for its price."
  },
  "SS:Bull Shark": {
    "role": "anti-air battleship",
    "strength": 10162,
    "rank": 7,
    "type": "Heavy assault battleship built around anti-air and missile defence. 159 m, 15,372 blocks.",
    "speed": "47.1 m/s (92 kn).",
    "fightsAt": "1,600 m.",
    "sees": "Eight radars (five passive, two tracking), infrared cameras, six laser rangefinders, two sonar sets, 39 warners and 18 laser warners.",
    "summary": "Anti-air fortress. Twenty-four heat-seekers, six flak guns, 62 interceptors — and a known design flaw: minor damage can detonate the main turret, though it stays afloat. Designers: 38 battle points, difficulty 3; 1.5× vs air.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "88th percentile"
      },
      "toughness": {
        "score": 5,
        "why": "93rd percentile — 1.04× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "57th percentile"
      },
      "range": {
        "score": 5,
        "why": "92nd percentile"
      },
      "cost": {
        "score": 5,
        "why": "93rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "twin 240 mm squash-head guns, six EMP torpedoes, six guided missiles; designers 0.7×"
      },
      "aircraft": {
        "score": 4,
        "why": "24 heat-seeking missiles, six 155 mm flak guns, twin 240 mm airburst; designers 1.5×"
      },
      "submarines": {
        "score": 2,
        "why": "six EMP torpedoes, two sonar sets; designers 0.6×"
      },
      "missiles": {
        "score": 5,
        "why": "62 interceptors, laser point-defence, 28 shields, close-in gun with 10 controllers, 39 warners, smoke"
      }
    },
    "verdict": "anti-air fortress",
    "verdictDetail": "Firepower 0.76× and toughness 1.04× the per-material medians for its price."
  },
  "SS:Tiger Shark": {
    "role": "missile cruiser",
    "strength": 13380,
    "rank": 5,
    "type": "Missile cruiser — the strongest craft on this list by the game's own number. 147 m, 11,906 blocks.",
    "speed": "45.4 m/s (88 kn).",
    "fightsAt": "1,500 m.",
    "sees": "Six radars (three passive, two tracking), eight laser rangefinders, an infrared camera, two sonar sets, 20 warners and 14 laser warners.",
    "summary": "Missile fortress. Ninety guided missiles, 66 interceptors, 27 shields. Designers: 50 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "93rd percentile"
      },
      "toughness": {
        "score": 5,
        "why": "94th percentile — 1.05× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "56th percentile"
      },
      "range": {
        "score": 5,
        "why": "87th percentile"
      },
      "cost": {
        "score": 5,
        "why": "94th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "82 radar-guided missiles, eight heavy guided missiles, six EMP torpedoes, twin 250 mm; designers 0.8×"
      },
      "aircraft": {
        "score": 4,
        "why": "82 radar-guided missiles plus flak and close-in guns"
      },
      "submarines": {
        "score": 2,
        "why": "six EMP torpedoes, two sonar sets; designers 0.8×"
      },
      "missiles": {
        "score": 5,
        "why": "66 interceptors, 27 shields, close-in gun, 20 warners, 24 smoke"
      }
    },
    "verdict": "missile fortress",
    "verdictDetail": "Firepower 0.98× and toughness 1.05× the per-material medians for its price — a balanced heavyweight."
  },
  "SS:Tyr": {
    "role": "flagship battleship",
    "strength": 9109,
    "rank": 9,
    "type": "The flagship — an \"all guns forward\" super-battleship. 211 m, 19,375 blocks.",
    "speed": "42.2 m/s (82 kn).",
    "fightsAt": "2,000 m — the longest reach on this list, shared with the Excalibur.",
    "sees": "Thirteen radars (six tracking), nine laser rangefinders, six sonar sets, infrared and camera trackers, 21 warners and 14 laser warners, six rangefinders.",
    "summary": "Flagship tank. Nine 380 mm armour-piercing guns, 88 interceptors, the toughest hull on this list; nothing under water. Designers: 50 battle points, difficulty 3.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "93rd percentile"
      },
      "toughness": {
        "score": 5,
        "why": "97th percentile — 1.28× the per-material median for its price"
      },
      "speed": {
        "score": 3,
        "why": "53rd percentile"
      },
      "range": {
        "score": 5,
        "why": "98th percentile"
      },
      "cost": {
        "score": 5,
        "why": "95th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "nine 380 mm armour-piercing guns with 23 m barrels"
      },
      "aircraft": {
        "score": 2,
        "why": "eight heat-seeking missiles, three close-in flak guns; main guns on plain elevation mounts"
      },
      "submarines": {
        "score": 1,
        "why": "no torpedoes"
      },
      "missiles": {
        "score": 5,
        "why": "88 interceptors, 13 shields, three close-in guns with 6 controllers, 44 smoke dispensers, 4 heat decoys, 21 warners"
      }
    },
    "verdict": "flagship tank",
    "verdictDetail": "Firepower 0.91× and toughness 1.28× the per-material medians for its price."
  }
}
