// GENERATED by scripts/import-ship-profiles.ts from WF.cards.md — do not hand-edit.
// Re-run the importer on a fresh report instead; shared/shipProfiles.test.ts pins
// every key here to a seeded card.
import type { ShipProfile } from '../shipProfiles.ts'

export const WF_SHIP_PROFILES: Record<string, ShipProfile> = {
  "WF:Martyr": {
    "role": "kamikaze nuke drone",
    "strength": 0,
    "rank": 44,
    "rankTied": true,
    "type": "Kamikaze jet drone — a 16 m airframe with two tactical nukes bolted on (game class: thruster craft). 97 blocks.",
    "speed": "106.7 m/s (207 kn) — very fast; flies at up to 508 m.",
    "fightsAt": "800 m — as close as anything in the campaign; it has to reach the hull.",
    "sees": "Nothing — no radar, camera, sonar or even a radio snooper on board.",
    "summary": "Suicide glass cannon. Two nukes on a paper airframe; the game's own blurb says battleships stop fighting each other to shoot it down. Designers: 1 battle point, difficulty 1.",
    "scores": {
      "firepower": {
        "score": 1,
        "why": "13th percentile — the game gives the two nukes 8 points"
      },
      "toughness": {
        "score": 1,
        "why": "bottom of the campaign — 1 M armoured health"
      },
      "speed": {
        "score": 5,
        "why": "85th percentile"
      },
      "range": {
        "score": 1,
        "why": "1st percentile"
      },
      "cost": {
        "score": 1,
        "why": "4th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "two tactical nukes if it gets there; anything with close-in guns swats it first"
      },
      "aircraft": {
        "score": 1,
        "why": "designers rate it 0× vs air"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 1,
        "why": "speed only"
      }
    },
    "verdict": "suicide glass cannon",
    "verdictDetail": "Firepower 3.9× and toughness 0.10× the per-material median of craft its price — the purest glass cannon in the fleet; it is spent, not lost."
  },
  "WF:Earth Raker": {
    "role": "spinning-claw ram boat",
    "strength": 0,
    "rank": 44,
    "rankTied": true,
    "type": "Ram boat with two spinning claw blocks on the bow, named for a mythical sea beast whose flippers scarred the ocean floor. 51 m, 1,546 blocks.",
    "speed": "88.1 m/s (171 kn) — very fast; quicker than 9 in 10 ships.",
    "fightsAt": "1,000 m — the typical distance, then it closes to zero.",
    "sees": "Only a radio snooper — it borrows what the rest of the fleet sees.",
    "summary": "Armoured rammer. 416 rams on a heavy-armour bow and nothing else. Designers: 20 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "31st percentile — all of it rams (0.1 each)"
      },
      "toughness": {
        "score": 3,
        "why": "41st percentile; 86th among craft of its price"
      },
      "speed": {
        "score": 4,
        "why": "78th percentile"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 2,
        "why": "23rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "ram damage scales with collision speed and it is very fast — but only wood and light metal give way"
      },
      "aircraft": {
        "score": 1,
        "why": "designers rate it 0.1× vs air"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 1,
        "why": "no warners, interceptors, shields or decoys"
      }
    },
    "verdict": "armoured rammer",
    "verdictDetail": "Firepower 1.4× and toughness 2.3× the per-material median for its price — cheap, fast, hard to kill, one trick."
  },
  "WF:Buzzsaw": {
    "role": "saw-blade ram boat",
    "strength": 54,
    "rank": 41,
    "type": "Ram boat carrying saw blades — seven spinning blocks of rams that 24 pistons push out from the hull; the Flayers' icon. 87 m, 2,656 blocks.",
    "speed": "90.5 m/s (176 kn) — very fast; quicker than 9 in 10 ships.",
    "fightsAt": "1,000 m.",
    "sees": "One radar, a camera with two trackers, a radio snooper. No sonar, no missile warners.",
    "summary": "Ram tank. 467 rams and one small gun on a hull twice as tough as its price class. Its blurb promises shields and missiles — this blueprint carries neither. Designers: 25 battle points, difficulty 1.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "36th percentile — 88 % of it rams"
      },
      "toughness": {
        "score": 3,
        "why": "51st percentile; 81st among craft of its price"
      },
      "speed": {
        "score": 4,
        "why": "79th percentile"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 2,
        "why": "34th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "saw blades at 90 m/s shred wood and light metal; armour stops them"
      },
      "aircraft": {
        "score": 1,
        "why": "one 30 mm gun on an anti-air mount; designers 0.1×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 1,
        "why": "no warners, interceptors, shields or decoys"
      }
    },
    "verdict": "ram tank",
    "verdictDetail": "Firepower 0.9× and toughness 2.2× the per-material median for its price."
  },
  "WF:Pontus": {
    "role": "drill submarine",
    "strength": 0,
    "rank": 44,
    "rankTied": true,
    "type": "Drill boat the game classes as a submarine — two 5 m steam drill heads on 16 shaft segments. 52 m, 777 blocks.",
    "speed": "34.2 m/s (66 kn) — quicker than 2 in 3 ships; its designers tell it to cruise.",
    "fightsAt": "800 m — as close as anything; the drills only bite on contact.",
    "sees": "Six sonar sets and a radio snooper. No radar, no cameras, no warners.",
    "summary": "Tough and toothless — on paper. The game counts no firepower for drills, so it scores 0; in play it grinds whatever it can park against. Designers: 15 battle points, difficulty 1.",
    "scores": {
      "firepower": {
        "score": 1,
        "why": "2nd percentile — 0; drills are not scored"
      },
      "toughness": {
        "score": 2,
        "why": "38th percentile; 73rd among craft of its price"
      },
      "speed": {
        "score": 3,
        "why": "45th percentile overall; 69th among ships"
      },
      "range": {
        "score": 1,
        "why": "1st percentile"
      },
      "cost": {
        "score": 2,
        "why": "26th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 1,
        "why": "two drill heads; it must sit against the target to use them"
      },
      "aircraft": {
        "score": 1,
        "why": "designers 0×"
      },
      "submarines": {
        "score": 1,
        "why": "six sonars find them; only the drills can touch them"
      },
      "missiles": {
        "score": 1,
        "why": "nothing"
      }
    },
    "verdict": "tough and toothless — on paper",
    "verdictDetail": "Toughness 1.9× the per-material median for its price, firepower 0× because the game does not score drills; treat it as a nuisance that grinds anything it reaches."
  },
  "WF:Pulverizer": {
    "role": "melee particle boat",
    "strength": 0,
    "rank": 44,
    "rankTied": true,
    "type": "Melee particle boat the game classes as a submarine; rides on 18 hydrofoils with a beam strung between two lenses. 52 m, 1,097 blocks.",
    "speed": "27.6 m/s (54 kn) — average for a ship.",
    "fightsAt": "900 m — closer than 19 in 20 craft; it has to touch you.",
    "sees": "Two sonar sets and a radio snooper. No radar, no cameras.",
    "summary": "Glass cannon. A close-range particle beam on a thin hull; designers rate it 1.6× vs surface targets. Designers: 15 battle points, difficulty 1.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "48th percentile — all of it the particle beam"
      },
      "toughness": {
        "score": 2,
        "why": "20th percentile; 17th among craft of its price"
      },
      "speed": {
        "score": 2,
        "why": "37th percentile; 56th among ships"
      },
      "range": {
        "score": 1,
        "why": "5th percentile"
      },
      "cost": {
        "score": 2,
        "why": "32nd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "a constant beam between two lenses fed by 243 m of particle tube — deadly to whatever drives into it"
      },
      "aircraft": {
        "score": 1,
        "why": "designers 0×"
      },
      "submarines": {
        "score": 1,
        "why": "sonar, but the beam only reaches what it touches"
      },
      "missiles": {
        "score": 2,
        "why": "5 shields and a jammer; no warners or interceptors"
      }
    },
    "verdict": "glass cannon",
    "verdictDetail": "Firepower 1.9× and toughness 0.45× the per-material median for its price."
  },
  "WF:The Repentance": {
    "role": "repair aircraft with missiles",
    "strength": 1254,
    "rank": 23,
    "type": "Repair-and-cargo aircraft (game class: thruster craft) that also carries a missile battery — 15 repair tentacles mend the fleet around it. 80 m long, 33 m wide, 2,316 blocks.",
    "speed": "88.2 m/s (171 kn) — fast; flies at up to 174 m.",
    "fightsAt": "3,000 m — the longest stand-off distance in the campaign (shared with two other craft).",
    "sees": "Two tracking radars, a camera, a laser rangefinder. No sonar, no missile warners.",
    "summary": "Armed support aircraft. Sixteen radar missiles and a close-in gun on a repair ship that keeps its distance.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "52nd percentile — 79 % of it the close-in gun"
      },
      "toughness": {
        "score": 3,
        "why": "42nd percentile"
      },
      "speed": {
        "score": 4,
        "why": "78th percentile"
      },
      "range": {
        "score": 5,
        "why": "99th percentile"
      },
      "cost": {
        "score": 3,
        "why": "40th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "16 medium radar missiles with two explosive warheads each, fired from 3 km"
      },
      "aircraft": {
        "score": 3,
        "why": "the same radar-guided missiles plus a 48 mm gun on an anti-air mount; designers 1×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "one close-in gun; no warners, interceptors, shields or decoys"
      }
    },
    "verdict": "armed support aircraft",
    "verdictDetail": "Firepower 1.75× and toughness 1.2× the per-material median for its price — a brawler's numbers on a craft whose job is to hang back and repair."
  },
  "WF:Basher": {
    "role": "laser-guided missile ship",
    "strength": 3976,
    "rank": 14,
    "type": "Missile ship built around one huge and six large laser-designated missiles. 94 m, 2,985 blocks.",
    "speed": "36.6 m/s (71 kn) — quicker than 7 in 10 ships.",
    "fightsAt": "950 m — closer than 9 in 10 craft.",
    "sees": "Radar (one all-round, two trackers), cameras with three trackers, four laser rangefinders. No sonar, no missile warners.",
    "summary": "Leans glass. Seven big laser-guided missiles on a thin alloy hull; strength rank 14 of 65 Flayer designs. Designers: 35 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "68th percentile — 96 % missiles"
      },
      "toughness": {
        "score": 3,
        "why": "51st percentile; 34th among craft of its price"
      },
      "speed": {
        "score": 3,
        "why": "48th percentile; 73rd among ships"
      },
      "range": {
        "score": 1,
        "why": "7th percentile"
      },
      "cost": {
        "score": 3,
        "why": "59th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "six 15-block missiles with five frag warheads each and one huge kinetic missile, all steered onto a laser spot; designers 1.5× vs surface"
      },
      "aircraft": {
        "score": 2,
        "why": "designers say 1× vs air, but slow heavy missiles and one small particle gun are a poor fit for aircraft"
      },
      "submarines": {
        "score": 1,
        "why": "no sonar; designers 0.5×"
      },
      "missiles": {
        "score": 2,
        "why": "6 shields, a flare and a radar-decoy launcher; no warners or interceptors"
      }
    },
    "verdict": "leans glass cannon",
    "verdictDetail": "Firepower 1.3× and toughness 0.72× the per-material median for its price."
  },
  "WF:Pandemonium": {
    "role": "fast particle ram ship",
    "strength": 432,
    "rank": 33,
    "type": "Fast ram ship with a particle turret — 428 rams on a heavy-armour bow, eight lenses on one turret above. 64 m long, 27 m wide, 27 m tall, 3,647 blocks.",
    "speed": "104.9 m/s (204 kn) — the fastest ship on this list; quicker than 19 in 20 ships.",
    "fightsAt": "1,100 m.",
    "sees": "Cameras with two trackers, two infrared trackers, four laser rangefinders, 18 missile warners, a radio snooper. No radar, no sonar.",
    "summary": "Balanced rammer. Particle turret and rams at 200 knots; tough for its price. Designers: 30 battle points, difficulty 3, 1.8× vs surface.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "61st percentile — about 70 % particle cannon, the rest rams"
      },
      "toughness": {
        "score": 4,
        "why": "67th percentile; 63rd among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "85th percentile"
      },
      "range": {
        "score": 4,
        "why": "60th percentile"
      },
      "cost": {
        "score": 4,
        "why": "64th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "an eight-lens particle turret on 432 m of tube, then 428 rams at 105 m/s; designers 1.8×"
      },
      "aircraft": {
        "score": 1,
        "why": "designers 0.1×; nothing built for aircraft"
      },
      "submarines": {
        "score": 1,
        "why": "no sonar, nothing reaches under water"
      },
      "missiles": {
        "score": 3,
        "why": "18 interceptors cued by 18 warners, four close-in controllers; no shields or decoys"
      }
    },
    "verdict": "balanced rammer",
    "verdictDetail": "Firepower 0.86× and toughness 1.14× the per-material median for its price — the fleet's fast armoured fist rather than a gunboat."
  },
  "WF:Scourge": {
    "role": "sandblaster missile cruiser",
    "strength": 2165,
    "rank": 19,
    "type": "Cruiser with two hypervelocity 31 mm \"sandblaster\" turrets, a vertical-launch missile battery and thick missile defence. 118 m, 4,493 blocks.",
    "speed": "27.9 m/s (54 kn) — average for a ship.",
    "fightsAt": "1,000 m.",
    "sees": "Two tracking radars and a passive radar, an active and a passive sonar, cameras with two trackers, two infrared cameras, two laser rangefinders, 28 missile warners, 12 laser warners, a retroreflection sensor, a radio snooper — full coverage.",
    "summary": "Sturdy brawler. Small fast darts by the hundred plus 16 radar missiles, on a hull tougher than its price.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "66th percentile — 76 % guns"
      },
      "toughness": {
        "score": 4,
        "why": "67th percentile; 75th among craft of its price"
      },
      "speed": {
        "score": 2,
        "why": "38th percentile"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 3,
        "why": "59th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "two 31 mm guns firing sabot darts behind 17 propellant casings, 23 belt-fed loaders each — a hail of small hard hits; 16 medium missiles with three frag warheads"
      },
      "aircraft": {
        "score": 3,
        "why": "16 radar-guided frag missiles and two fast-firing hypervelocity turrets; designers 1×"
      },
      "submarines": {
        "score": 2,
        "why": "one sonar set, and a supercavitating sabot round made to reach under water"
      },
      "missiles": {
        "score": 4,
        "why": "23 interceptors, 28 warners, 6 shields, 3 smoke, two close-in controllers on the guns"
      }
    },
    "verdict": "sturdy brawler",
    "verdictDetail": "Firepower 1.3× and toughness 1.5× the per-material median for its price."
  },
  "WF:Veles": {
    "role": "melee particle ram cruiser",
    "strength": 1155,
    "rank": 24,
    "type": "Fast ram cruiser with four melee particle lenses along the hull, a gun, missiles and torpedoes. 81 m long, 31 m wide, 5,453 blocks.",
    "speed": "76.9 m/s (149 kn) — fast; quicker than 9 in 10 ships.",
    "fightsAt": "1,000 m.",
    "sees": "Two tracking radars, two passive radars, six cameras, 6 missile warners. No sonar.",
    "summary": "Brawler. 543 rams and a particle beam it drives through you at 150 knots; average toughness for its price. Designers: 28 battle points, difficulty 2.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "77th percentile — about two-thirds particle beam, then rams, gun and missiles"
      },
      "toughness": {
        "score": 4,
        "why": "67th percentile"
      },
      "speed": {
        "score": 4,
        "why": "72nd percentile"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 4,
        "why": "69th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "four melee lenses on 398 m of tube, 543 rams, a 60 mm gun, six radar cluster missiles, three torpedoes"
      },
      "aircraft": {
        "score": 2,
        "why": "one 60 mm gun on an anti-air mount and six small radar missiles with a single frag warhead; designers 0.7×"
      },
      "submarines": {
        "score": 1,
        "why": "three sonar torpedoes but no sonar to find a target with; designers 0×"
      },
      "missiles": {
        "score": 3,
        "why": "8 interceptors, 10 decoy launchers, 6 shields, 6 smoke, 6 warners, two close-in controllers"
      }
    },
    "verdict": "brawler",
    "verdictDetail": "Firepower 1.4× and toughness 0.96× the per-material median for its price."
  },
  "WF:Disemboweler": {
    "role": "heavy particle submarine",
    "strength": 808,
    "rank": 25,
    "type": "Submarine (the game's own class) built around the biggest particle cannon on this list. 98 m long, 30 m wide, 3,072 blocks.",
    "speed": "43.0 m/s (84 kn) — quicker than 4 in 5 ships.",
    "fightsAt": "1,000 m.",
    "sees": "Eight sonar sets plus an all-round active and a passive sonar, a radio snooper. No radar, no cameras, no missile warners.",
    "summary": "Glass cannon. 1,084 m of particle tube behind two big lenses on a thin metal hull; 10th highest firepower of 65 Flayer designs, 25th toughest. Designers: 10 battle points, 1× vs submarines, 0× vs air.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "91st percentile — 99 % particle cannon"
      },
      "toughness": {
        "score": 3,
        "why": "53rd percentile; 18th among craft of its price"
      },
      "speed": {
        "score": 3,
        "why": "53rd percentile; 79th among ships"
      },
      "range": {
        "score": 2,
        "why": "32nd percentile"
      },
      "cost": {
        "score": 4,
        "why": "70th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "two large accelerator lenses (\"a damage boost and a wide field of fire, but loses lots of damage at medium-long ranges\") and two small ones on 1,084 m of tube"
      },
      "aircraft": {
        "score": 1,
        "why": "designers 0×; nothing tracks aircraft"
      },
      "submarines": {
        "score": 3,
        "why": "designers 1× vs undersea and ten sonar sets; whether the beams reach down is not something the tool can tell"
      },
      "missiles": {
        "score": 2,
        "why": "32 torpedo-propelled interceptors for torpedoes and a sonar decoy; no missile warners, shields or smoke"
      }
    },
    "verdict": "glass cannon",
    "verdictDetail": "Firepower 2.4× and toughness 0.46× the per-material median for its price."
  },
  "WF:Slasher": {
    "role": "big-gun cruiser",
    "strength": 3093,
    "rank": 17,
    "type": "Big-gun cruiser — a twin 300 mm sabot turret on a long alloy hull with heavy armour. 155 m, 8,383 blocks.",
    "speed": "27.9 m/s (54 kn) — average for a ship.",
    "fightsAt": "1,300 m.",
    "sees": "One radar, two active and two passive sonar sets, three infrared trackers, cameras, two laser rangefinders, 14 missile warners, a radio snooper.",
    "summary": "Tank. Two long 300 mm sabot guns and a lot of hull; strength rank 17 of 65. Designers: 30 battle points, difficulty 1.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "72nd percentile — 94 % guns"
      },
      "toughness": {
        "score": 5,
        "why": "80th percentile; 79th among craft of its price"
      },
      "speed": {
        "score": 2,
        "why": "38th percentile"
      },
      "range": {
        "score": 4,
        "why": "75th percentile"
      },
      "cost": {
        "score": 4,
        "why": "73rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "twin 300 mm guns with 19 m barrels firing 5 m sabot darts from 64 loaders — long-range armour piercing; designers 1.1×"
      },
      "aircraft": {
        "score": 2,
        "why": "a 49 mm and a 30 mm close-in gun on anti-air mounts; gun-only"
      },
      "submarines": {
        "score": 1,
        "why": "sees under water (two sonar sets) but the sabot round has no supercavitation; designers 1×"
      },
      "missiles": {
        "score": 4,
        "why": "20 interceptors (8 torpedo-propelled, for torpedoes), 14 warners, 8 shields, two close-in guns with four controllers"
      }
    },
    "verdict": "tank",
    "verdictDetail": "Firepower 0.97× and toughness 1.4× the per-material median for its price."
  },
  "WF:The Last Rite": {
    "role": "drill rotor gunship",
    "strength": 1731,
    "rank": 21,
    "type": "Four-rotor gunship (game class: thruster craft) with six pecking drill arms, a 38 m drill lance and missiles. 111 m long, 65 m wide, 4,723 blocks.",
    "speed": "118.9 m/s (231 kn) — the fastest craft on this list; flies at up to 208 m.",
    "fightsAt": "1,200 m.",
    "sees": "Four tracking radars, cameras with four trackers, two infrared cameras, two sonar sets, 14 laser warners, a radio snooper. No missile warners.",
    "summary": "Armoured drill-pecker; firepower uncounted. The game scores it 7 because drills count for nothing — its designers rate it 2× vs surface targets. Designers: 28 battle points, difficulty 1.",
    "scores": {
      "firepower": {
        "score": 1,
        "why": "12th percentile — 7, all missiles; the drills are not scored"
      },
      "toughness": {
        "score": 4,
        "why": "70th percentile; 72nd among craft of its price"
      },
      "speed": {
        "score": 5,
        "why": "90th percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 4,
        "why": "63rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "seven drill heads that hover and peck, four large laser-guided missiles, six radar cluster missiles, two bombs and a mine; designers 2×"
      },
      "aircraft": {
        "score": 2,
        "why": "six medium radar-guided missiles; designers 0.5×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "6 shields, 3 smoke and a smoke generator, speed; no interceptors or missile warners"
      }
    },
    "verdict": "tank on paper, drill-pecker in play",
    "verdictDetail": "Toughness 1.5× the per-material median for its price; the 0.04× firepower ratio is the game not scoring drills, not a verdict on the craft."
  },
  "WF:Judgement": {
    "role": "particle battleship",
    "strength": 1477,
    "rank": 22,
    "type": "Particle battleship — three twin-lens particle turrets fed by 1,470 m of tube, the largest array on this list. 174 m, 7,774 blocks.",
    "speed": "35.0 m/s (68 kn) — quicker than 7 in 10 ships.",
    "fightsAt": "1,200 m.",
    "sees": "Radar (two all-round, two 90-degree, two trackers), three passive sonar sets, cameras and infrared cameras, six laser rangefinders, 14 missile warners, 7 laser warners, a retroreflection sensor, a radio snooper.",
    "summary": "Balanced, a little soft for its price. Six particle lenses, 43 interceptors and 60 reactive-armour blocks. Designers: 25 battle points, difficulty 3.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "82nd percentile — 98 % particle cannon"
      },
      "toughness": {
        "score": 4,
        "why": "79th percentile; 36th among craft of its price"
      },
      "speed": {
        "score": 3,
        "why": "46th percentile; 70th among ships"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 5,
        "why": "83rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "rated from play: three turrets of two cross-input lenses each on 1,470 m of tube — and nothing else"
      },
      "aircraft": {
        "score": 4,
        "why": "rated from play: the turrets can elevate, though nothing is built for aircraft; designers 0.8×"
      },
      "submarines": {
        "score": 4,
        "why": "rated from play: three passive sonar sets and 11 torpedo-propelled interceptors; designers 1× vs undersea"
      },
      "missiles": {
        "score": 4,
        "why": "43 interceptors, 14 warners, 10 shields, 29 smoke dispensers, 60 ERA"
      }
    },
    "verdict": "balanced, leaning soft",
    "verdictDetail": "Firepower 1.0× and toughness 0.84× the per-material median for its price."
  },
  "WF:Excruciator": {
    "role": "railgun hydrofoil battleship",
    "strength": 3502,
    "rank": 15,
    "type": "Railgun battleship on 630 hydrofoils — four 200 mm railguns with 26 m barrels. 180 m long, 41 m wide, 33 m tall, 11,235 blocks.",
    "speed": "53.7 m/s (104 kn) — fast for its size; quicker than 6 in 7 ships.",
    "fightsAt": "1,400 m — longer than 4 in 5 craft.",
    "sees": "Radar (one all-round, two 90-degree, three trackers, one passive), two sonar sets and a passive sonar, cameras and infrared cameras, twelve laser rangefinders, 10 missile warners, 9 laser warners — full coverage.",
    "summary": "Heavyweight brawler. Top-quintile firepower, toughness, range and cost, and fast; 8th toughest and 9th hardest-hitting Flayer design.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "92nd percentile — 98 % guns"
      },
      "toughness": {
        "score": 5,
        "why": "93rd percentile; 81st among craft of its price"
      },
      "speed": {
        "score": 4,
        "why": "60th percentile; 86th among ships"
      },
      "range": {
        "score": 5,
        "why": "80th percentile"
      },
      "cost": {
        "score": 5,
        "why": "88th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "four 200 mm railguns (rail charge 200,000, 104 chargers each) firing supercavitating sabot darts — pure armour piercing"
      },
      "aircraft": {
        "score": 2,
        "why": "eight small radar missiles (warhead not identified) and railguns on elevation mounts; gun-only in practice"
      },
      "submarines": {
        "score": 3,
        "why": "the sabot round has a supercavitation base to reach under water; three sonar sets; 8 torpedo-propelled interceptors"
      },
      "missiles": {
        "score": 5,
        "why": "50 interceptors on 16 close-in controllers, 21 shields, 8 heat decoys and a radar decoy, 5 smoke, 19 warners, a jammer"
      }
    },
    "verdict": "heavyweight brawler",
    "verdictDetail": "Firepower 1.2× and toughness 1.4× the per-material median for its price — above the line on both, and fast."
  },
  "WF:Purifier": {
    "role": "railgun battleship",
    "strength": 4805,
    "rank": 12,
    "type": "Railgun battleship — seven railgun-driven guns in three single turrets and one quad, plus three anti-air particle turrets. 238 m long, 46 m tall, 15,158 blocks (only 43 campaign craft are bigger).",
    "speed": "26.6 m/s (52 kn) — average for a ship.",
    "fightsAt": "1,700 m — longer than 9 in 10 craft.",
    "sees": "Everything: radar (two all-round, two 90-degree, three trackers, one passive), three active and three passive sonar sets, nine cameras with six trackers, nine infrared cameras, six rangefinders, 8 missile warners, 18 laser warners, a retroreflection sensor, a radio snooper. Two AI mainframes.",
    "summary": "Heavyweight tank. Top-quintile firepower, toughness, range and cost; 82 interceptors; slow. 12th strongest Flayer design.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "90th percentile — 92 % guns"
      },
      "toughness": {
        "score": 5,
        "why": "94th percentile; 81st among craft of its price"
      },
      "speed": {
        "score": 2,
        "why": "36th percentile"
      },
      "range": {
        "score": 5,
        "why": "93rd percentile"
      },
      "cost": {
        "score": 5,
        "why": "90th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "a quad 273 mm turret (rail charge 200,000) and three 250 mm turrets, 24–25 m barrels, AP-frag rounds driven by rails alone"
      },
      "aircraft": {
        "score": 2,
        "why": "three small anti-air particle turrets (58 m of tube each) — instant-hit but light; the main guns are on elevation mounts"
      },
      "submarines": {
        "score": 1,
        "why": "six sonar sets see them; only two drop mines reach them"
      },
      "missiles": {
        "score": 5,
        "why": "82 interceptors (42 torpedo-propelled) on eight close-in controllers, 24 shields, 15 smoke, two flare launchers, 26 warners"
      }
    },
    "verdict": "heavyweight tank",
    "verdictDetail": "Firepower 1.0× and toughness 1.3× the per-material median for its price; the most of everything in absolute terms, at 52 knots."
  }
}
