// GENERATED by scripts/import-ship-profiles.ts from DWG.cards.md — do not hand-edit.
// Re-run the importer on a fresh report instead; shared/shipProfiles.test.ts pins
// every key here to a seeded card.
import type { ShipProfile } from '../shipProfiles.ts'

export const DWG_SHIP_PROFILES: Record<string, ShipProfile> = {
  "DWG:Corsair": {
    "role": "escort boat",
    "strength": 415,
    "rank": 69,
    "type": "Small escort boat that guards loot convoys. 53 m, 1,727 blocks.",
    "speed": "21.3 m/s (41 kn) — average for a boat.",
    "fightsAt": "1,000 m — the typical distance.",
    "sees": "One radar, one sonar, a camera, 10 missile warners.",
    "summary": "Expendable anti-air picket. Radar missiles on turrets, nothing that can take a hit.",
    "scores": {
      "firepower": {
        "score": 1,
        "why": "18th percentile"
      },
      "toughness": {
        "score": 1,
        "why": "16th percentile — 16 M armoured health"
      },
      "speed": {
        "score": 2,
        "why": "31st percentile"
      },
      "range": {
        "score": 2,
        "why": "33rd percentile"
      },
      "cost": {
        "score": 1,
        "why": "14th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "eight small radar missiles and one 174 mm gun"
      },
      "aircraft": {
        "score": 3,
        "why": "radar-guided missiles on turrets; designers rate it 1.5× vs air"
      },
      "submarines": {
        "score": 1,
        "why": "has a sonar, nothing to fire at what it finds"
      },
      "missiles": {
        "score": 2,
        "why": "10 warners and two flare launchers; no interceptors or guns"
      }
    },
    "verdict": "expendable",
    "verdictDetail": "Firepower 0.8× and toughness 0.9× the per-material median of craft its price — an ordinary cheap boat; anything serious kills it."
  },
  "DWG:Marauder": {
    "role": "obsolete gunboat",
    "strength": 624,
    "rank": 56,
    "type": "Obsolete mass-produced gunboat, now sold off as target practice. 71 m, 3,133 blocks.",
    "speed": "7.8 m/s (15 kn) — a crawl; slower than 5 in 6 craft.",
    "fightsAt": "900 m — shorter than 19 in 20 craft.",
    "sees": "Three cameras and a rangefinder. No radar, sonar or missile warners.",
    "summary": "Target practice. One fortress-busting cannon on a hull that cannot move, see or defend itself.",
    "scores": {
      "firepower": {
        "score": 2,
        "why": "34th percentile — mostly 56 swivel guns"
      },
      "toughness": {
        "score": 2,
        "why": "24th percentile"
      },
      "speed": {
        "score": 1,
        "why": "17th percentile"
      },
      "range": {
        "score": 1,
        "why": "5th percentile"
      },
      "cost": {
        "score": 1,
        "why": "19th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 2,
        "why": "one 2,000 mm CRAM shell at a time, and it cannot catch anything"
      },
      "aircraft": {
        "score": 1,
        "why": "designers rate it 0.1× vs air"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 1,
        "why": "no warners, interceptors, guns or decoys"
      }
    },
    "verdict": "target practice",
    "verdictDetail": "Firepower 1.8× the per-material median for its price (the swivel guns count), toughness 1.1× — on paper fine, in practice it is too slow and blind to use either."
  },
  "DWG:Loggerhead": {
    "role": "flying submarine",
    "strength": 6278,
    "rank": 2,
    "type": "Submarine (the game's own class for it) that can also fly, up to 98 m. 72 m long, 49 m wide, 7,382 blocks.",
    "speed": "57.2 m/s (111 kn) — fast; quicker than 7 in 8 ships.",
    "fightsAt": "1,500 m.",
    "sees": "Four sonar sets, cameras with three telescope trackers, 6 warners. No radar — its missiles carry their own.",
    "summary": "Flying submarine. Ambushes from under water, chases from the air; leans glass for its price.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "81st percentile — 2nd strongest pirate craft"
      },
      "toughness": {
        "score": 4,
        "why": "64th percentile, but only 32nd among craft of its price"
      },
      "speed": {
        "score": 4,
        "why": "62nd percentile"
      },
      "range": {
        "score": 5,
        "why": "87th percentile"
      },
      "cost": {
        "score": 4,
        "why": "72nd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "12 torpedoes, 10 large radar missiles, 8 shaped-charge missiles, 8 CRAM guns"
      },
      "aircraft": {
        "score": 3,
        "why": "10 large radar-guided missiles and two 257 mm anti-air-mount guns"
      },
      "submarines": {
        "score": 4,
        "why": "12 sonar torpedoes, four sonar sets, and it can dive itself"
      },
      "missiles": {
        "score": 3,
        "why": "8 interceptors, 9 shields, 6 warners, one flare launcher"
      }
    },
    "verdict": "leans glass cannon",
    "verdictDetail": "Firepower 1.5× and toughness 0.68× the per-material median for its price; it lives on surprise, speed and being under water rather than on armour."
  },
  "DWG:Flying Squirrel": {
    "role": "flight of 3 missile planes",
    "strength": 625,
    "rank": 55,
    "type": "A flight of three small missile aircraft built from scrap, 296 blocks each (24 m long).",
    "speed": "95 m/s (185 kn) — very fast; flies at up to 200 m.",
    "fightsAt": "800 m — closer than almost anything; it must fly in.",
    "sees": "Two all-round radars per aircraft, plus radio snoopers.",
    "note": "Firepower and toughness below are for one aircraft (the game rates each craft on its own); cost is for the flight.",
    "summary": "Pure glass cannon. Four missiles per plane, no armour; fires and dies.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "55th percentile — for one plane"
      },
      "toughness": {
        "score": 1,
        "why": "2nd percentile — 2 M armoured health per plane"
      },
      "speed": {
        "score": 5,
        "why": "82nd percentile"
      },
      "range": {
        "score": 1,
        "why": "2nd percentile"
      },
      "cost": {
        "score": 2,
        "why": "33rd percentile (the flight)"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "12 radar-guided missiles across the flight, 6 of them large; designers rate it 1.5× vs surface"
      },
      "aircraft": {
        "score": 2,
        "why": "the same missiles can chase aircraft, but there are few and no guns"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "a flare launcher per plane and speed"
      }
    },
    "verdict": "pure glass cannon",
    "verdictDetail": "Per plane, roughly 7× the firepower per material of craft its price and about a tenth of the toughness — the flimsiest craft on this list."
  },
  "DWG:Pilferer": {
    "role": "gun raider",
    "strength": 1087,
    "rank": 41,
    "type": "\"Pocket battleship\" gun raider. 97 m, 3,670 blocks.",
    "speed": "15.2 m/s (30 kn) — slow; 3 in 4 ships are quicker.",
    "fightsAt": "1,000 m.",
    "sees": "Cameras with two telescope trackers, four rangefinders, 7 warners. No radar, no sonar.",
    "summary": "Fragile gun raider. Six 250 mm high-explosive guns that wreck wooden ships and bounce off armour.",
    "scores": {
      "firepower": {
        "score": 3,
        "why": "55th percentile, all cannon"
      },
      "toughness": {
        "score": 2,
        "why": "36th percentile; 29th among craft of its price"
      },
      "speed": {
        "score": 2,
        "why": "24th percentile"
      },
      "range": {
        "score": 2,
        "why": "33rd percentile"
      },
      "cost": {
        "score": 3,
        "why": "48th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "six 250 mm HE guns — short-ranged, one propellant casing, big blast on wood"
      },
      "aircraft": {
        "score": 1,
        "why": "one 50 mm close-in gun; main guns on plain elevation mounts; designers 0.8×"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "one close-in gun, two flare launchers, 7 warners"
      }
    },
    "verdict": "leans glass cannon",
    "verdictDetail": "Firepower 1.4× and toughness 0.61× the per-material median for its price."
  },
  "DWG:Abactor": {
    "role": "old broadside gunship",
    "strength": 2102,
    "rank": 24,
    "type": "Old-fashioned broadside gunship on sail-era lines (53 m tall). 99 m, 7,992 blocks.",
    "speed": "16.1 m/s (31 kn) — slow.",
    "fightsAt": "1,200 m.",
    "sees": "Three telescope trackers, cameras, three rangefinders. No radar, sonar or missile warners.",
    "summary": "Sturdy brawler, slow and half-blind. Punches and takes punches above its price.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "68th percentile — 90 % of it CRAM"
      },
      "toughness": {
        "score": 3,
        "why": "57th percentile; 68th among craft of its price"
      },
      "speed": {
        "score": 2,
        "why": "27th percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 3,
        "why": "52nd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "four 1,600 mm CRAM guns, eight casemate CRAM guns, three torpedoes"
      },
      "aircraft": {
        "score": 2,
        "why": "four 75 mm anti-air guns and two heat-seeking missiles; designers 0.8×"
      },
      "submarines": {
        "score": 2,
        "why": "three sonar torpedoes; designers 0.9×"
      },
      "missiles": {
        "score": 2,
        "why": "heat and radar decoys, two smoke generators; no warners, interceptors or guns"
      }
    },
    "verdict": "brawler",
    "verdictDetail": "Firepower 1.9× and toughness 1.25× the per-material median for its price — an old hull that outperforms its cost, as its designers boast."
  },
  "DWG:Ransack": {
    "role": "fast light cruiser",
    "strength": 3020,
    "rank": 12,
    "type": "Fast light cruiser that whittles enemies down from range. 106 m, 6,272 blocks.",
    "speed": "32.7 m/s (64 kn) — quicker than 2 in 3 ships.",
    "fightsAt": "1,200 m.",
    "sees": "Three sonar sets, two telescope trackers, cameras, four rangefinders, 5 warners. No radar.",
    "summary": "Balanced kiter. Normal toughness, but packed with ammunition — when it goes, it goes up.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "66th percentile"
      },
      "toughness": {
        "score": 3,
        "why": "50th percentile"
      },
      "speed": {
        "score": 3,
        "why": "43rd percentile overall; 65th among ships"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 3,
        "why": "53rd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "five 200 mm incendiary/frag guns, four torpedoes, two missiles"
      },
      "aircraft": {
        "score": 2,
        "why": "the 200 mm guns are on anti-air mounts with a flak shell, but no anti-air missiles"
      },
      "submarines": {
        "score": 2,
        "why": "four sonar torpedoes and three sonar sets"
      },
      "missiles": {
        "score": 4,
        "why": "12 interceptors (4 of them torpedo-propelled, for enemy torpedoes), four flare launchers, four shields, flak"
      }
    },
    "verdict": "balanced",
    "verdictDetail": "Firepower 1.7× and toughness 0.99× the per-material median for its price. Its own description warns it is stuffed with ammo and \"pops spectacularly\" when hit."
  },
  "DWG:Paddlegun": {
    "role": "paddle-wheel gunboat",
    "strength": 2552,
    "rank": 16,
    "type": "Paddle-wheel gunboat with two long-barrelled triple turrets. 85 m, 5,441 blocks.",
    "speed": "21.1 m/s (41 kn) — average for a ship.",
    "fightsAt": "1,000 m.",
    "sees": "Four all-round cameras, 6 warners. No radar, no sonar.",
    "summary": "Balanced gunboat. Very long, accurate guns; average toughness for its price.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "61st percentile"
      },
      "toughness": {
        "score": 3,
        "why": "54th percentile"
      },
      "speed": {
        "score": 2,
        "why": "30th percentile"
      },
      "range": {
        "score": 2,
        "why": "33rd percentile"
      },
      "cost": {
        "score": 3,
        "why": "57th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 3,
        "why": "six 140 mm high-velocity incendiary guns and six large frag missiles"
      },
      "aircraft": {
        "score": 3,
        "why": "gun-only, but the designers rate it 2× vs air — the highest on this list — for its all-round turrets and 26 m barrels. Check in play."
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 2,
        "why": "two flak close-in guns, 6 warners, two shields, one decoy; no interceptors"
      }
    },
    "verdict": "balanced",
    "verdictDetail": "Firepower 1.1× and toughness 0.89× the per-material median for its price; its designers call it one of the most dangerous pirate ships of its size."
  },
  "DWG:Plunderer": {
    "role": "CRAM battleship",
    "strength": 3562,
    "rank": 9,
    "type": "Battleship on a stolen Steel Striders design with captured Onyx Watch CRAM cannons; paddle-driven. 126 m long, 65 m wide, 11,871 blocks.",
    "speed": "27.4 m/s (53 kn) — average for a ship.",
    "fightsAt": "1,500 m.",
    "sees": "Seven radars, four sonar sets, cameras with two telescope trackers, six rangefinders, 6 warners — full coverage.",
    "summary": "Armoured brawler. Nine big CRAM guns behind 94 reactive-armour blocks; slow and weak against air. Designers: 40 battle points, difficulty 3.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "77th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "69th percentile — 5th toughest pirate craft"
      },
      "speed": {
        "score": 2,
        "why": "37th percentile"
      },
      "range": {
        "score": 5,
        "why": "87th percentile"
      },
      "cost": {
        "score": 4,
        "why": "69th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "nine 2,000 mm CRAM guns with hardened HE/frag shells, four torpedoes, six radar missiles"
      },
      "aircraft": {
        "score": 2,
        "why": "four 140 mm airburst guns and five close-in guns; designers 0.5×"
      },
      "submarines": {
        "score": 2,
        "why": "four sonar torpedoes and sonar; designers 0.5×"
      },
      "missiles": {
        "score": 3,
        "why": "five close-in guns with 8 controllers, eight flare launchers, 6 warners; no interceptors, no shields"
      }
    },
    "verdict": "brawler",
    "verdictDetail": "Firepower 1.4× and toughness 1.07× the per-material median for its price."
  },
  "DWG:Buccaneer": {
    "role": "airship battleship",
    "strength": 3518,
    "rank": 10,
    "type": "Airship battleship — a flying fortress (up to 196 m altitude) with an onboard pub. 116 m long, 47 m wide, 14,172 blocks.",
    "speed": "82.7 m/s (161 kn) — fast; quicker than 9 in 10 ships.",
    "fightsAt": "1,500 m.",
    "sees": "Four radars (two tracking), laser rangefinders, an infrared camera, eight rangefinders, 11 warners. No sonar.",
    "summary": "Flying brawler. Eighteen CRAM guns rain shells on targets below; nothing to shoot at aircraft. Designers: 45 battle points.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "81st percentile — 72 % of it CRAM"
      },
      "toughness": {
        "score": 4,
        "why": "71st percentile — 4th toughest pirate craft"
      },
      "speed": {
        "score": 4,
        "why": "76th percentile"
      },
      "range": {
        "score": 5,
        "why": "87th percentile"
      },
      "cost": {
        "score": 4,
        "why": "70th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "18 CRAM guns (4 quad + 4 twin-turret + 10 hull), most with hardener"
      },
      "aircraft": {
        "score": 1,
        "why": "one downward-firing 50 mm gun; CRAM cannot track aircraft; no anti-air missiles"
      },
      "submarines": {
        "score": 1,
        "why": "no sonar, nothing reaches under water"
      },
      "missiles": {
        "score": 3,
        "why": "6 interceptors, 11 warners, two radar decoys"
      }
    },
    "verdict": "brawler",
    "verdictDetail": "Firepower 1.6× and toughness 1.2× the per-material median for its price, and fast for its size — but blind to submarines and defenceless against aircraft."
  },
  "DWG:Sinners Luck": {
    "role": "broadside CRAM ship",
    "strength": 4438,
    "rank": 5,
    "type": "Captain Goldwater's floating palace turned broadside warship. 112 m, 10,071 blocks.",
    "speed": "19.3 m/s (38 kn) — below average.",
    "fightsAt": "1,000 m — it wants to get alongside.",
    "sees": "Two all-round radars, five telescope trackers, 9 warners. No sonar.",
    "summary": "Close-range brawler, leaning glass. Twenty-six CRAM guns and sixteen torpedoes on a palace hull.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "80th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "61st percentile; 41st among craft of its price"
      },
      "speed": {
        "score": 2,
        "why": "29th percentile"
      },
      "range": {
        "score": 2,
        "why": "33rd percentile"
      },
      "cost": {
        "score": 4,
        "why": "66th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "24 broadside CRAM guns, a twin 2,000 mm turret, 16 torpedoes, 4 large missiles"
      },
      "aircraft": {
        "score": 2,
        "why": "twelve small flak gatlings and four 30 mm guns — gun-only"
      },
      "submarines": {
        "score": 2,
        "why": "sixteen sonar torpedoes but no sonar to find a submarine with"
      },
      "missiles": {
        "score": 3,
        "why": "twelve flak gatlings with 8 close-in controllers, 9 warners, three smoke generators; no interceptors or shields"
      }
    },
    "verdict": "brawler leaning glass",
    "verdictDetail": "Firepower 1.8× and toughness 0.78× the per-material median for its price; short-ranged, so it must survive the approach."
  },
  "DWG:Albacore": {
    "role": "aerial battlecruiser",
    "strength": 3638,
    "rank": 8,
    "type": "Aerial battlecruiser (flies at up to 126 m). 92 m long, 55 m wingspan, 8,364 blocks.",
    "speed": "79.7 m/s (155 kn) — fast.",
    "fightsAt": "1,200 m.",
    "sees": "Three telescope trackers, a camera, three rangefinders, 20 warners. No radar, no sonar.",
    "summary": "Flying brawler. Quad CRAM turret plus long-barrelled cannons; exactly average toughness for its price.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "79th percentile"
      },
      "toughness": {
        "score": 4,
        "why": "65th percentile"
      },
      "speed": {
        "score": 4,
        "why": "74th percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 4,
        "why": "66th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "four 2,000 mm CRAM, four 400 mm and two ~500 mm long guns, two large missiles"
      },
      "aircraft": {
        "score": 2,
        "why": "four 130 mm airburst guns — gun-only"
      },
      "submarines": {
        "score": 1,
        "why": "nothing reaches under water"
      },
      "missiles": {
        "score": 3,
        "why": "8 interceptors, 20 warners, two radar decoys, two smoke"
      }
    },
    "verdict": "brawler",
    "verdictDetail": "Firepower 1.7× the per-material median for its price at exactly 1.0× toughness; fast, but thin against air and blind under water."
  },
  "DWG:Kraken": {
    "role": "shield cruiser",
    "strength": 4328,
    "rank": 6,
    "type": "Shield-heavy torpedo-and-gun cruiser. 60 m long, 39 m wide, 6,074 blocks.",
    "speed": "12.7 m/s (25 kn) — slow; 4 in 5 ships are quicker.",
    "fightsAt": "1,200 m.",
    "sees": "One sonar, five cameras, 12 warners. No radar.",
    "summary": "Glass hull behind a wall of shields. 38 shield projectors; a weak hull underneath. Designers: 30 battle points, difficulty 3.",
    "scores": {
      "firepower": {
        "score": 4,
        "why": "73rd percentile"
      },
      "toughness": {
        "score": 3,
        "why": "49th percentile; 11th among craft of its price (shields not counted)"
      },
      "speed": {
        "score": 2,
        "why": "22nd percentile"
      },
      "range": {
        "score": 4,
        "why": "67th percentile"
      },
      "cost": {
        "score": 4,
        "why": "70th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "four large torpedoes, three shaped-charge missiles, nine cannons"
      },
      "aircraft": {
        "score": 1,
        "why": "one 20 mm gun; the cannons are on plain elevation mounts with no flak design"
      },
      "submarines": {
        "score": 2,
        "why": "four heavy sonar torpedoes and one sonar; designers 0.5×"
      },
      "missiles": {
        "score": 3,
        "why": "38 shields and 12 warners, but only 4 interceptors and no close-in guns"
      }
    },
    "verdict": "glass hull behind shields",
    "verdictDetail": "Toughness 0.42× the per-material median for its price, firepower 1.1× — hard to hurt while the shields are up, fragile once they drop, and too slow to leave."
  },
  "DWG:Brigand": {
    "role": "missile destroyer",
    "strength": 5849,
    "rank": 3,
    "type": "Missile destroyer — a pirate copy of a Steel Striders destroyer. 113 m, 7,305 blocks.",
    "speed": "26.6 m/s (52 kn) — average for a ship.",
    "fightsAt": "1,850 m — the longest reach on this list.",
    "sees": "Four tracking radars, four sonar sets, cameras with five trackers, 10 warners — full coverage.",
    "escort": "The Gull gyrocopter (350 blocks): 18 mm strafing gun, one heat-seeking and one radar-guided missile, flares.",
    "summary": "Glass cannon. Sixty-six launchers and two flak cannons on a wooden hull; shields are its armour.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "82nd percentile — 58 % missiles"
      },
      "toughness": {
        "score": 3,
        "why": "52nd percentile; 13th among craft of its price"
      },
      "speed": {
        "score": 2,
        "why": "37th percentile"
      },
      "range": {
        "score": 5,
        "why": "95th percentile"
      },
      "cost": {
        "score": 4,
        "why": "74th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 4,
        "why": "six heavy missiles, six 7-warhead torpedoes, 32 medium missiles; the guns have no armour-piercing round"
      },
      "aircraft": {
        "score": 4,
        "why": "36 radar-guided missiles plus two 200 mm flak cannons on anti-air mounts"
      },
      "submarines": {
        "score": 2,
        "why": "six sonar torpedoes and four sonar sets; nothing else reaches under water"
      },
      "missiles": {
        "score": 4,
        "why": "14 interceptors, a flak close-in gun, chaff, 10 warners, 11 shields"
      }
    },
    "verdict": "glass cannon",
    "verdictDetail": "Firepower 1.5× and toughness 0.38× the per-material median for its price."
  },
  "DWG:Crossbones": {
    "role": "CRAM battleship, flagship",
    "strength": 7118,
    "rank": 1,
    "type": "CRAM battleship built from salvaged wrecks — the pirates' flagship; paddle-wheel driven. 182 m, 20,098 blocks (only 16 campaign craft are bigger).",
    "speed": "21.0 m/s (41 kn) — slow.",
    "fightsAt": "1,500 m.",
    "sees": "Eight radars, cameras with two telescope trackers, ten rangefinders, 6 warners. No sonar.",
    "summary": "Brawler, not glass cannon. Twenty two-metre cannons; ordinary toughness for its price; loses to a pair of Predator-X jets. Designers: 50 battle points, difficulty 3.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "94th percentile — strongest pirate craft"
      },
      "toughness": {
        "score": 4,
        "why": "79th percentile; 47th among craft of its price"
      },
      "speed": {
        "score": 2,
        "why": "30th percentile"
      },
      "range": {
        "score": 5,
        "why": "87th percentile"
      },
      "cost": {
        "score": 5,
        "why": "80th percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "twenty 2,000 mm CRAM guns with hardened HE shells; designers 1.4× vs surface"
      },
      "aircraft": {
        "score": 2,
        "why": "gun-only: 180°-spray frag rounds that armoured aircraft shrug off; loses to two Predator-X"
      },
      "submarines": {
        "score": 1,
        "why": "no sonar, no torpedoes"
      },
      "missiles": {
        "score": 3,
        "why": "seven close-in guns, 18 shields, 6 warners; no interceptors, chaff or flares"
      }
    },
    "verdict": "brawler",
    "verdictDetail": "Firepower 1.8× and toughness 0.94× the per-material median for its price. Dies to aircraft and torpedoes, not to gunfire."
  },
  "DWG:Tarpon": {
    "role": "flying gun platform",
    "strength": 5837,
    "rank": 4,
    "type": "Flying gun platform (up to 332 m altitude) — Captain Die-Zell's debt collector, war horn included. 138 m long, 83 m tall, 15,420 blocks.",
    "speed": "70.4 m/s (137 kn) — fast for its size.",
    "fightsAt": "1,500 m.",
    "sees": "One radar, a laser tracker, two telescope trackers, cameras, five rangefinders, 32 missile warners. No sonar.",
    "summary": "Heavyweight all-rounder. Top-quintile firepower, toughness, range and cost, and fast; nothing reaches under water.",
    "scores": {
      "firepower": {
        "score": 5,
        "why": "89th percentile — the most cannon firepower of any pirate craft"
      },
      "toughness": {
        "score": 5,
        "why": "82nd percentile — 2nd toughest pirate craft"
      },
      "speed": {
        "score": 4,
        "why": "68th percentile"
      },
      "range": {
        "score": 5,
        "why": "87th percentile"
      },
      "cost": {
        "score": 5,
        "why": "82nd percentile"
      }
    },
    "matchups": {
      "ships": {
        "score": 5,
        "why": "two ~500 mm guns with 54 m barrels, four CRAM guns, two 211 mm guns, two heavy torpedoes"
      },
      "aircraft": {
        "score": 2,
        "why": "two 211 mm anti-air-mount guns and three 45 mm close-in guns — gun-only"
      },
      "submarines": {
        "score": 1,
        "why": "two sonar torpedoes but no sonar to find a submarine with"
      },
      "missiles": {
        "score": 4,
        "why": "15 interceptors, three close-in guns with 5 controllers, 32 warners, 11 shields, four radar decoys"
      }
    },
    "verdict": "heavyweight all-rounder",
    "verdictDetail": "Firepower 1.3× and toughness 1.03× the per-material median for its price — nothing exceptional per material, but the most of everything in absolute terms after the Crossbones, and it flies."
  }
}
